# -*- coding: utf-8 -*-
"""STEP ARM 概念的领域分类。

提供三个正交的分类维度，每个概念可同时命中多个类别（多标签）：

* ``INDUSTRY``  —— 应用领域（航空、汽车、造船、机械、电气、通用）
* ``USERS``     —— 主要使用者（领域专家、工程师、标准制定者）
* ``LIFECYCLE`` —— 产品生命周期功能环节（CAD / CAM / CAE / PDM / CAPP / 检测质量 / 通用基础）

匹配对象为「概念名 + 所属模块名」的小写拼接串，因此模块名也会参与判定
（例如 ``machining_features`` 模块下的全部概念都会命中「机械」与「CAM」）。

用法::

    from arm_domains import classify
    classify("Machining_feature", "machining_features")
    # -> {"industry": ["机械 / 装备制造"], "users": [...], "lifecycle": ["CAM（制造 / 加工）", ...]}
"""
import collections
import re

# --------------------------------------------------------------------------
# 维度 A：应用领域
# --------------------------------------------------------------------------
INDUSTRY = collections.OrderedDict([
    ("航空 / 航天", [
        r"composite", r"ply", r"laminate", r"assembly", r"airframe",
        r"aerodynamic", r"wing", r"fuselage", r"spar", r"stringer",
        r"kinematic", r"mechanism", r"interpolated_configuration",
        r"link_motion", r"joint", r"oriented_joint", r"breakdown",
        r"functional_element", r"physical_element",
    ]),
    ("汽车 / 车辆", [
        r"gear", r"pair", r"mechanism", r"kinematic", r"chamfer", r"fillet",
        r"knurl", r"thread", r"boss", r"pocket", r"slot", r"rib", r"recess",
        r"protrusion", r"groove", r"hole", r"cutout", r"pattern", r"marking",
        r"surface_condition", r"surface_texture", r"hardness", r"coating",
        r"tolerance", r"datum", r"dimension", r"solid_model", r"brep", r"csg",
    ]),
    ("造船 / 船舶", [
        r"shell", r"surface_patch", r"composite_curve", r"composite_surface",
        r"rectangular_composite", r"plate", r"profile", r"stiffener",
        r"manifold_surface", r"shell_based_surface", r"non_manifold",
        r"geometrically_bounded_surface", r"curve_bounded_surface",
        r"trimmed_surface", r"offset_surface", r"swept_surface",
        r"surface_of_revolution", r"surface_set", r"connected_face",
        r"surface", r"curve",
    ]),
    ("机械 / 装备制造", [
        r"machining", r"manufacturing", r"feature", r"hole", r"slot",
        r"pocket", r"thread", r"gear", r"knurl", r"chamfer", r"fillet",
        r"round", r"boss", r"rib", r"recess", r"protrusion", r"groove",
        r"cutout", r"pattern", r"tolerance", r"datum", r"dimension",
        r"kinematic", r"pair", r"mechanism", r"joint", r"link", r"tool",
        r"workpiece", r"setup", r"process_plan", r"process_operation",
        r"work_order", r"work_request", r"resource", r"fabrication",
        r"additive_manufacturing", r"build_volume", r"build_platform",
        r"surface_condition", r"surface_texture", r"hardness", r"coating",
        r"marking", r"solid_model", r"brep", r"csg", r"primitive",
        r"tessellated", r"triangulated", r"scan", r"point_cloud",
    ]),
    ("电气 / 电子 / 物理量", [
        r"electric_", r"magnetic_", r"capacitance", r"conductance",
        r"inductance", r"resistance", r"luminous", r"illuminance",
        r"radioactivity", r"dose_equivalent", r"absorbed_dose", r"power_",
        r"energy", r"force", r"pressure", r"thermal", r"thermodynamic",
        r"frequency", r"velocity", r"acceleration", r"mass", r"volume",
        r"area", r"length", r"angle", r"solid_angle", r"ratio",
        r"amount_of_substance", r"celsius_temperature", r"dielectric_constant",
        r"loss_tangent", r"hardness", r"_data_element", r"_unit$",
        r"value_with_unit", r"numerical_item_with_unit",
    ]),
])

# --------------------------------------------------------------------------
# 维度 B：主要使用者
# --------------------------------------------------------------------------
USERS = collections.OrderedDict([
    ("领域专家（业务 / 管理）", [
        r"product", r"part", r"assembly", r"breakdown", r"requirement",
        r"specification", r"process_plan", r"process_operation", r"work_order",
        r"work_request", r"project", r"contract", r"activity", r"document",
        r"approval", r"certification", r"person", r"organization",
        r"effectivity", r"configuration", r"class", r"property", r"group",
        r"event", r"date", r"time", r"market", r"supplier", r"solution",
        r"resource", r"material", r"security", r"information", r"retention",
        r"alias", r"external_source", r"language", r"multi_linguism",
        r"test_specification", r"design_specification",
        r"process_specification", r"surface_finish_specification",
        r"fabrication_technology_specification", r"interface_specification",
        r"occurrence", r"structure", r"version", r"identification",
        r"tracing_relationship", r"make_from_relationship",
        r"alternate_part_relationship", r"alternate_product_relationship",
        r"supplied_part_relationship", r"replaced_usage_relationship",
        r"promissory_usage", r"quantified_instance", r"single_instance",
        r"selected_instance", r"specified_occurrence", r"specified_product",
        r"design_constraint", r"design_specification",
        r"management_resource_information", r"resource_item",
        r"resource_requirement_type", r"data_environment",
        r"known_source", r"incomplete_reference_marking",
        r"incomplete_data_reference_mechanism", r"file", r"hardcopy",
        r"digital_file", r"address", r"environment",
    ]),
    ("工程师（几何 / 工艺 / 公差）", [
        r"geometry", r"geometric", r"topology", r"topological", r"curve",
        r"surface", r"solid", r"shell", r"face", r"edge", r"vertex", r"loop",
        r"point", r"line", r"plane", r"circle", r"ellipse", r"hyperbola",
        r"parabola", r"conic", r"spline", r"bezier", r"torus", r"cylinder",
        r"cone", r"sphere", r"pyramid", r"wedge", r"hexahedron",
        r"tetrahedron", r"block", r"brep", r"csg", r"manifold", r"half_space",
        r"boolean", r"swept", r"extruded", r"revolved", r"tessellated",
        r"triangulated", r"placement", r"transformation", r"direction",
        r"vector", r"axis", r"tolerance", r"datum", r"dimension", r"feature",
        r"hole", r"slot", r"pocket", r"thread", r"gear", r"knurl", r"chamfer",
        r"fillet", r"round", r"boss", r"rib", r"recess", r"protrusion",
        r"groove", r"cutout", r"pattern", r"machining", r"manufacturing",
        r"process", r"workpiece", r"setup", r"tool", r"kinematic", r"pair",
        r"mechanism", r"joint", r"link", r"motion", r"material", r"appearance",
        r"colour", r"style", r"presentation", r"draughting", r"annotation",
        r"text", r"symbol", r"marker", r"font", r"fill_area", r"hatch",
        r"tile", r"light_source", r"camera", r"view", r"scan", r"point_cloud",
        r"measure", r"unit", r"value", r"uncertainty", r"surface_condition",
        r"surface_texture", r"hardness", r"coating", r"marking", r"gps",
        r"characteristic", r"limits_and_fits", r"precision", r"qualifier",
        r"numeric", r"expression", r"function", r"literal", r"variable",
        r"shape", r"layer", r"presentation_set", r"view_area",
    ]),
    ("标准制定者（元模型 / 表达 / 库）", [
        r"expression", r"function", r"literal", r"variable", r"generic",
        r"representation", r"representation_context", r"representation_item",
        r"representation_relationship", r"external_library", r"external_class",
        r"plib", r"otd_catalogue", r"otd_dictionary", r"iso15926",
        r"user_defined_library", r"class_by_extension", r"class_by_intension",
        r"class_hierarchy", r"class_system", r"classification_system",
        r"specification_category", r"structuring_method", r"value_format",
        r"precision_qualifier", r"type_qualifier", r"uncertainty_qualifier",
        r"measure_qualification", r"qualified_", r"maths_value",
        r"number_of_decimal_places", r"significant_number_of_digits",
        r"derived_unit", r"conversion_based_unit", r"context_dependent_unit",
        r"external_source", r"external_representation_item",
        r"external_item_identification", r"external_string_representation_item",
        r"externally_defined_", r"pre_defined_", r"user_defined_",
        r"defined_function", r"defined_character_glyph", r"defined_gear",
        r"defined_marking", r"defined_thread",
        r"sql_mappable_defined_function", r"data_environment",
        r"incomplete_reference_marking", r"incomplete_data_reference_mechanism",
        r"known_source", r"file", r"file_relationship",
        r"file_location_identification", r"digital_file", r"hardcopy",
        r"document_location_identification", r"uniform_resource_identifier",
        r"language_reference_manual", r"multi_level_reference_designator",
        r"component_upper_level_identification",
        r"identification_assignment", r"name_assignment", r"address_assignment",
        r"attribute_translation_assignment", r"attribute_classification",
        r"classification_assignment", r"classification_association",
        r"classification_attribute", r"collected_item_association",
        r"collection_definition", r"sequence_representation_item",
        r"set_representation_item", r"null_representation_item",
        r"rational_representation_item", r"compound_representation_item",
        r"representation_reference", r"representation_context_reference",
        r"definitional_representation", r"parametric_representation_context",
        r"numerical_representation_context",
        r"geometric_representation_context_with_parameter",
        r"path_parameter_representation_context", r"view_definition_context",
        r"additional_view_definition_context",
        r"initial_view_definition_context", r"external_geometric_model",
        r"external_library_property", r"external_model",
        r"externally_defined_representation",
        r"externally_defined_type_qualifier", r"pre_defined_type_qualifier",
        r"plib_class_reference", r"plib_dictionary", r"plib_library",
        r"plib_property_reference", r"otd_",
    ]),
])

# --------------------------------------------------------------------------
# 维度 C：产品生命周期功能环节
# --------------------------------------------------------------------------
LIFECYCLE = collections.OrderedDict([
    ("CAD（设计 / 建模 / 制图）", [
        r"geometry", r"geometric", r"topology", r"topological", r"curve",
        r"surface", r"solid", r"shell", r"face", r"edge", r"vertex", r"loop",
        r"point", r"line", r"plane", r"circle", r"ellipse", r"hyperbola",
        r"parabola", r"conic", r"spline", r"bezier", r"torus", r"cylinder",
        r"cone", r"sphere", r"pyramid", r"wedge", r"hexahedron",
        r"tetrahedron", r"block", r"brep", r"csg", r"manifold", r"half_space",
        r"boolean", r"swept", r"extruded", r"revolved", r"tessellated",
        r"triangulated", r"placement", r"transformation", r"direction",
        r"vector", r"axis", r"feature", r"hole", r"slot", r"pocket", r"thread",
        r"gear", r"knurl", r"chamfer", r"fillet", r"round", r"boss", r"rib",
        r"recess", r"protrusion", r"groove", r"cutout", r"pattern", r"shape",
        r"draughting", r"annotation", r"dimension", r"tolerance", r"datum",
        r"appearance", r"colour", r"style", r"presentation", r"text",
        r"symbol", r"marker", r"font", r"fill_area", r"hatch", r"tile",
        r"light_source", r"camera", r"view", r"scan", r"point_cloud",
        r"material", r"surface_condition", r"surface_texture", r"hardness",
        r"coating", r"marking", r"gps", r"characteristic", r"limits_and_fits",
        r"precision", r"qualifier", r"measure", r"unit", r"value",
        r"uncertainty", r"representation", r"expression", r"function",
        r"literal", r"variable", r"numeric", r"layer", r"presentation_set",
        r"view_area", r"view_definition_context", r"geometric_model",
        r"constructive_geometry", r"compound_shape_representation",
        r"compound_representation_item", r"geometric_placeholder_set",
        r"geometric_placement", r"geometric_placement_model",
        r"geometric_placement_operation", r"geometric_composition",
        r"geometric_operator_transformation", r"geometric_relationship",
        r"geometrical_relationship", r"geometric_alignment",
        r"geometric_contact", r"geometric_intersection",
        r"geometric_coordinate_space", r"geometric_dimension",
        r"detailed_geometric_model_element", r"detailed_topological_model_element",
        r"nominal_3d", r"model_geometric_view", r"default_model_geometric_view",
        r"contextual_shape_representation", r"shape_element",
        r"shape_feature_definition", r"shape_profile", r"shape_composition",
        r"shape_description_association", r"shape_property_assignment",
        r"derived_shape_element", r"offset_shape_element",
        r"composite_shape_element", r"compound_feature",
        r"feature_definition_with_connection_area", r"connection_zone",
        r"placed_feature", r"instanced_feature", r"replicate_feature",
        r"replicate_base", r"multi_axis_feature", r"profile_feature",
        r"transition_feature", r"general_feature", r"general_part_feature",
        r"general_removal_volume", r"general_revolution", r"general_boss",
        r"general_cutout", r"general_pocket", r"general_pattern",
        r"general_profile", r"general_closed_profile", r"general_open_profile",
        r"general_outside_profile", r"general_shape_profile",
        r"general_top_condition", r"general_pocket_bottom_condition",
        r"general_profile_floor", r"general_rib_top_floor",
        r"general_tolerance", r"general_tolerances", r"general_tolerance_table",
        r"general_symbol", r"general_material_property",
        r"general_datum_reference", r"general_linear_function",
    ]),
    ("CAM（制造 / 加工）", [
        r"machining", r"manufacturing", r"process_plan", r"process_operation",
        r"work_order", r"work_request", r"workpiece", r"setup", r"tool",
        r"resource", r"fabrication", r"additive_manufacturing", r"build_volume",
        r"build_platform", r"surface_condition", r"surface_texture", r"thread",
        r"knurl", r"marking", r"feature", r"hole", r"slot", r"pocket",
        r"chamfer", r"fillet", r"groove", r"cutout", r"pattern", r"recess",
        r"protrusion", r"boss", r"rib", r"same_time_machining",
        r"instanced_manufacturing_feature", r"manufacturing_feature",
        r"manufacturing_feature_group", r"manufacturing_configuration",
        r"process_specification", r"fabrication_technology_specification",
        r"treatment_result", r"coating_layer", r"surface_finish_specification",
        r"process_property", r"process_state", r"process_operation_definition",
        r"process_operation_occurrence", r"process_operation_input_or_output",
        r"process_operation_resource_assignment", r"process_plan_relationship",
        r"process_property_assignment", r"process_product_association",
        r"process_state_relationship", r"resource_item",
        r"resource_item_assignment", r"resource_item_realization",
        r"resource_item_relationship", r"resource_requirement_type",
        r"resource_group_relationship", r"management_resource_information",
        r"tool_attachment_point_frame", r"tool_centre_point_frame",
        r"build_platform_definition", r"circular_build_volume",
        r"rectangular_build_volume", r"additive_manufacturing_build_direction_element",
        r"additive_manufacturing_orientation_element",
        r"additive_manufacturing_part_definition",
        r"additive_manufacturing_setup", r"additive_manufacturing_setup_build_plate",
        r"additive_manufacturing_support_structure",
        r"additive_manufacturing_support_structure_setup",
        r"additive_manufacturing_workpiece_setup",
        r"additive_manufacturing_workplan",
        r"additive_manufacturing_x_direction_element",
        r"machining_feature", r"machining_feature_size",
        r"manufacturing_configuration_effectivity",
        r"surface_finish_specification", r"surface_condition_callout",
        r"surface_condition_symbol", r"surface_texture_parameter",
        r"standard_surface_texture_parameter",
        r"user_defined_surface_texture_parameter",
        r"hardness", r"coating_layer", r"treatment_result",
        r"fabrication_technology_specification",
    ]),
    ("CAE（分析 / 仿真）", [
        r"kinematic", r"mechanism", r"pair", r"joint", r"link", r"motion",
        r"interpolated_configuration", r"material_property", r"measurement",
        r"uncertainty", r"statistical_tolerance", r"geometric_validation",
        r"test_specification", r"requirement", r"analysis", r"simulation",
        r"contact_ratio", r"geometric_contact", r"geometric_alignment",
        r"geometric_intersection", r"su_parameters", r"mechanism_state",
        r"mechanism_representation", r"kinematic_analysis",
        r"kinematic_control", r"kinematic_state", r"kinematic_property",
        r"kinematic_topology", r"kinematic_path", r"kinematic_link",
        r"kinematic_joint", r"kinematic_loop", r"product_definition_kinematics",
        r"product_definition_relationship_kinematics",
        r"product_structure_link_motion_association", r"link_motion",
        r"item_link_motion_relationship", r"rigid_link_representation",
        r"linear_flexible_link_representation",
        r"context_dependent_kinematic_link_representation",
        r"kinematic_analysis_consistency", r"kinematic_analysis_result",
        r"kinematic_link_representation", r"kinematic_link_representation_association",
        r"kinematic_path_defined_by_curves", r"kinematic_path_defined_by_nodes",
        r"kinematic_path_segment", r"kinematic_property_definition_representation",
        r"kinematic_property_mechanism_representation",
        r"kinematic_property_topology_representation",
        r"kinematic_topology_directed_structure",
        r"kinematic_topology_network_structure",
        r"kinematic_topology_structure", r"kinematic_topology_substructure",
        r"kinematic_topology_tree_structure", r"oriented_joint",
        r"actuated_kinematic_pair", r"high_order_kinematic_pair",
        r"low_order_kinematic_pair", r"low_order_kinematic_pair_with_motion_coupling",
        r"fully_constrained_pair", r"unconstrained_pair",
        r"cylindrical_pair", r"planar_pair", r"prismatic_pair",
        r"revolute_pair", r"screw_pair", r"spherical_pair",
        r"spherical_pair_with_pin", r"universal_pair", r"gear_pair",
        r"rack_and_pinion_pair", r"rolling_curve_pair", r"rolling_surface_pair",
        r"sliding_curve_pair", r"sliding_surface_pair", r"surface_pair",
        r"point_on_surface_pair", r"point_on_planar_curve_pair",
        r"planar_curve_pair", r"linear_flexible_and_pinion_pair",
        r"linear_flexible_and_planar_curve_pair", r"homokinetic_pair",
        r"pair_value", r"pair_representation_relationship",
        r"material_property", r"material_property_association",
        r"material_property_value_representation", r"general_material_property",
        r"measurement_path", r"measure_item", r"measure_representation",
        r"expanded_uncertainty", r"standard_uncertainty",
        r"qualitative_uncertainty", r"uncertainty_with_unit",
        r"representation_with_uncertainty", r"statistical_tolerance_characteristic",
        r"geometric_validation_property",
        r"geometric_validation_property_representation",
        r"test_specification", r"requirement_view_definition",
        r"requirement_view_definition_relationship",
        r"requirement_satisfied_by", r"requirement_source",
        r"requirement_version", r"requirement_version_relationship",
        r"requirement_collection_relationship",
        r"requirement_precedence_relationship",
        r"single_requirement_view_definition",
        r"requirement_identification_and_version",
        r"mechanical_design_requirement_item_association",
    ]),
    ("PDM（产品数据管理）", [
        r"product", r"part", r"version", r"configuration", r"effectivity",
        r"document", r"approval", r"certification", r"contract", r"project",
        r"work_order", r"person", r"organization", r"security",
        r"information_right", r"retention", r"alias", r"external_source",
        r"class", r"property", r"group", r"date", r"time", r"event",
        r"activity", r"breakdown", r"assembly", r"occurrence", r"structure",
        r"identification", r"name_assignment", r"address", r"language",
        r"multi_linguism", r"market", r"supplier", r"solution",
        r"requirement", r"specification", r"resource", r"material",
        r"file", r"hardcopy", r"digital_file", r"data_environment",
        r"external_library", r"external_class", r"plib", r"otd_",
        r"iso15926", r"user_defined_library", r"known_source",
        r"incomplete_reference_marking", r"incomplete_data_reference_mechanism",
        r"product_as_individual", r"product_as_planned", r"product_as_realized",
        r"product_design_to_individual", r"product_design_version_to_individual",
        r"product_design_view_to_individual", r"product_planned_to_realized",
        r"product_concept", r"product_class", r"product_category",
        r"product_configuration", r"product_occurrence", r"product_version",
        r"product_view_definition", r"product_resource", r"product_specification",
        r"part_version", r"part_view_definition", r"part_definition_relationship",
        r"part_occurrence", r"part_shape", r"part_function_association",
        r"part_collection", r"part_with_additional_categories",
        r"specified_occurrence", r"specified_product", r"specification_based",
        r"definition_based_product_occurrence", r"quantified_instance",
        r"single_instance", r"selected_instance", r"promissory_usage",
        r"replaced_usage_relationship", r"supplied_part_relationship",
        r"alternate_part_relationship", r"alternate_product_relationship",
        r"make_from_relationship", r"tracing_relationship",
        r"item_design_association", r"design_constraint",
        r"design_specification", r"design_product_data_management",
        r"pre_defined_product_data_management_specializations",
        r"management_resource_information", r"resource_item",
        r"resource_group_relationship", r"resource_requirement_type",
        r"product_version_resource", r"product_view_resource",
        r"process_operation_resource_assignment",
        r"activity_method", r"activity_method_assignment",
        r"activity_method_relationship", r"activity_property",
        r"activity_property_representation", r"activity_relationship",
        r"activity_status", r"directed_activity", r"applied_activity",
        r"applied_activity_method_assignment", r"externally_defined_activity",
        r"pre_defined_activity_relationship", r"work_request_status",
        r"work_request_relationship", r"work_order_relationship",
        r"externally_defined_work_request",
        r"externally_defined_work_request_status", r"pre_defined_work_request",
        r"pre_defined_work_request_status", r"approval_status",
        r"approval_relationship", r"approval_assignment",
        r"approving_person_organization", r"externally_defined_approval",
        r"externally_defined_approval_status", r"pre_defined_approval",
        r"pre_defined_approval_status", r"certification_assignment",
        r"contract_assignment", r"contract_relationship",
        r"project_assignment", r"project_relationship",
        r"person_in_organization", r"person_in_organization_relationship",
        r"organization_relationship",
        r"organization_or_person_in_organization_assignment",
        r"externally_defined_organization_or_person_in_organization_assignment",
        r"security_classification", r"security_classification_assignment",
        r"externally_defined_security_classification",
        r"pre_defined_security_classification", r"information_usage_right",
        r"information_usage_right_relationship",
        r"applied_information_usage_right", r"retention_period",
        r"alias_identification", r"external_source_identification",
        r"external_item_identification",
        r"external_item_identification_relationship",
        r"external_representation_item", r"external_string_representation_item",
        r"external_geometric_model", r"external_library_property",
        r"externally_defined_representation",
        r"externally_defined_type_qualifier", r"pre_defined_type_qualifier",
        r"pre_defined_colour", r"pre_defined_date_or_date_time_assignment",
        r"pre_defined_address_assignment",
        r"externally_defined_date_or_date_time_assignment",
        r"externally_defined_address_assignment",
        r"date_or_date_time_assignment", r"date_time_assignment",
        r"event_assignment", r"event_relationship", r"relative_event",
        r"time_interval", r"time_interval_assignment",
        r"time_interval_effectivity", r"time_interval_relationship",
        r"time_interval_role", r"time_interval_with_bounds", r"time_offset",
        r"dated_configuration", r"dated_effectivity", r"serial_effectivity",
        r"lot_effectivity", r"lot_configuration", r"serial_configuration",
        r"effectivity_assignment", r"effectivity_relationship",
        r"effectivity_controlled_assembly_definition",
        r"item_usage_effectivity", r"ineffectivity_assignment",
        r"manufacturing_configuration_effectivity",
        r"configuration_effectivity", r"specification_based_configuration",
        r"product_configuration_hierarchical_relationship",
        r"product_configuration_relationship",
        r"product_configuration_revision_sequence",
        r"class_breakdown_association", r"class_category_association",
        r"class_condition_association", r"class_inclusion_association",
        r"class_specification_association", r"class_with_attributes",
        r"classification_assignment_relationship", r"classification_system",
        r"external_class_with_attributes", r"attribute_classification",
        r"attribute_translation_assignment", r"name_assignment",
        r"address_assignment", r"identification_assignment",
        r"assigned_document_property", r"assigned_property",
        r"assigned_shape_property", r"applied_independent_property",
        r"applied_independent_property_relationship",
        r"applied_independent_activity_property",
        r"applied_independent_material_property", r"independent_property",
        r"independent_property_relationship",
        r"independent_property_representation", r"correlated_property",
        r"single_property_is_definition", r"property_definition_relationship",
        r"property_definition_representation", r"property_representation",
        r"property_value_representation",
        r"shape_dependent_property_representation",
        r"geometric_validation_property",
        r"geometric_validation_property_representation",
        r"default_shape_property", r"general_material_property",
        r"material_property", r"material_property_association",
        r"material_property_value_representation", r"material_identification",
        r"material_specification", r"group_relationship",
        r"collected_item_association", r"collection_definition",
        r"resource_group_relationship", r"breakdown_element",
        r"breakdown_element_definition", r"breakdown_element_realization",
        r"breakdown_element_usage", r"breakdown_element_version",
        r"breakdown_node_relationship", r"breakdown_of", r"breakdown_version",
        r"breakdown_context", r"functional_breakdown",
        r"functional_breakdown_context", r"functional_breakdown_version",
        r"functional_element", r"functional_element_definition",
        r"functional_element_usage", r"functional_element_version",
        r"physical_breakdown", r"physical_breakdown_context",
        r"physical_breakdown_version", r"physical_element",
        r"physical_element_definition", r"physical_element_placement",
        r"physical_element_usage", r"physical_element_version",
        r"complex_node_relationship", r"assembly_definition",
        r"assembly_component_relationship", r"assembly_relationship_substitution",
        r"assembled_part_association", r"next_assembly_usage",
        r"definitional_part_view_usage",
        r"product_occurrence_definition_relationship",
        r"product_occurrence_with_quantity", r"part_occurrence_placement",
        r"part_occurrence_relationship", r"occurrence_placement",
        r"product_definition_element_relationship",
        r"product_definition_exchange_context",
        r"product_structure_link_motion_association",
        r"product_version_relationship", r"product_view_definition_relationship",
        r"product_view_definition_reference",
        r"product_view_definition_reference_with_local_representation",
        r"part_definition_relationship", r"part_shape_element",
        r"part_shape_element_relationship", r"part_function_association",
        r"part_collection", r"part_with_additional_categories",
        r"generic_product_view_definition_reference",
        r"additional_part_view_definition_context",
        r"initial_part_view_definition_context", r"part_view_definition",
        r"part_version", r"product_identification", r"product_structure",
        r"product_version", r"product_view_definition", r"product_concept",
        r"product_concept_identification", r"product_categorization",
        r"product_category_assignment", r"product_category_hierarchy",
        r"product_class_relationship", r"product_replacement",
        r"product_as_individual", r"product_as_individual_version",
        r"product_as_individual_view", r"product_as_planned",
        r"product_as_realized", r"product_definition_kinematics",
        r"product_definition_relationship_kinematics", r"product_resource",
        r"product_specification", r"product_version_resource",
        r"product_view_resource", r"specified_product",
        r"specified_occurrence", r"test_select_product",
        r"quantified_instance", r"single_instance", r"selected_instance",
        r"promissory_usage", r"replaced_usage_relationship",
        r"supplied_part_relationship", r"alternate_part_relationship",
        r"alternate_product_relationship", r"make_from_relationship",
        r"tracing_relationship", r"item_design_association",
        r"design_constraint_association",
        r"design_constraint_context_association",
        r"design_constraint_definition", r"design_specification",
        r"design_product_data_management",
        r"pre_defined_product_data_management_specializations",
        r"management_resource_information", r"resource_item",
        r"resource_item_assignment", r"resource_item_realization",
        r"resource_item_relationship", r"resource_requirement_type",
        r"process_operation_resource_assignment",
    ]),
    ("CAPP（工艺规划）", [
        r"process_plan", r"process_operation", r"process_specification",
        r"process_state", r"process_operation_definition",
        r"process_operation_occurrence", r"process_operation_input_or_output",
        r"process_operation_resource_assignment", r"process_property",
        r"machining_feature", r"manufacturing_feature", r"feature",
        r"workplan", r"setup", r"workpiece", r"resource",
        r"fabrication_technology_specification",
        r"surface_finish_specification", r"treatment_result",
        r"coating_layer", r"same_time_machining",
        r"instanced_manufacturing_feature", r"manufacturing_feature_group",
        r"manufacturing_configuration", r"process_plan_relationship",
        r"process_operation_definition_relationship",
        r"process_operation_occurrence_relationship",
        r"process_property_assignment", r"process_product_association",
        r"process_state_relationship", r"machining_feature_size",
        r"additive_manufacturing_workplan",
        r"additive_manufacturing_part_definition",
        r"additive_manufacturing_setup", r"additive_manufacturing_workpiece_setup",
        r"additive_manufacturing_support_structure",
        r"additive_manufacturing_support_structure_setup",
        r"additive_manufacturing_setup_build_plate",
        r"build_platform_definition", r"build_volume",
        r"circular_build_volume", r"rectangular_build_volume",
        r"resource_item", r"resource_item_assignment",
        r"resource_item_realization", r"resource_item_relationship",
        r"resource_requirement_type", r"resource_group_relationship",
        r"management_resource_information",
        r"tool_attachment_point_frame", r"tool_centre_point_frame",
    ]),
    ("检测 / 质量（PMI / 计量）", [
        r"tolerance", r"dimension", r"datum", r"gps", r"uncertainty",
        r"surface_condition", r"surface_texture", r"measurement",
        r"test_specification", r"validation", r"certification",
        r"characteristic_data_table", r"value_range", r"limits_and_fits",
        r"precision_qualifier", r"type_qualifier", r"measure_qualification",
        r"qualified_", r"value_with_tolerances", r"plus_minus",
        r"upper_lower", r"tolerance_characteristic", r"tolerance_range",
        r"tolerance_table_cell", r"tolerance_zone", r"geometric_tolerance",
        r"dimensional_location", r"dimensional_size", r"angular_location",
        r"angular_size", r"curved_distance", r"curved_size",
        r"linear_distance", r"diameter_size", r"radial_size",
        r"thickness_size", r"outer_diameter", r"nominal_",
        r"statistical_tolerance", r"geometric_validation", r"measure_item",
        r"measure_representation", r"measurement_path", r"characteristic",
        r"range_characteristic", r"length_tolerance_characteristic",
        r"maximum_tolerance_characteristic",
        r"minimum_tolerance_characteristic",
        r"nominal_tolerance_characteristic",
        r"plus_minus_tolerance_characteristic",
        r"qualified_tolerance_characteristic",
        r"statistical_tolerance_characteristic",
        r"symmetrical_tolerance_characteristic",
        r"typical_tolerance_characteristic", r"general_tolerance",
        r"default_tolerance", r"general_tolerances",
        r"general_tolerance_table", r"surface_finish_specification",
        r"surface_condition_callout", r"surface_condition_symbol",
        r"surface_texture_parameter", r"standard_surface_texture_parameter",
        r"user_defined_surface_texture_parameter", r"hardness",
        r"gps_filter", r"gps_filtration_specification", r"datum_feature",
        r"datum_reference", r"datum_system", r"datum_target", r"common_datum",
        r"general_datum_reference", r"placed_target", r"dimension_callout",
        r"dimension_curve", r"dimension_prefix", r"dimension_suffix",
        r"dimension_symbol", r"dimension_text", r"dimension_value",
        r"dimension_sequence_pair", r"structured_dimension_callout",
        r"associated_dimension_text", r"geometric_tolerance_callout",
        r"geometric_tolerance_symbol", r"geometric_tolerance_relationship",
        r"geometric_tolerance_auxiliary_classification",
        r"datum_feature_callout", r"datum_target_callout",
        r"datum_reference_compartment", r"datum_reference_element",
        r"datum_reference_modifier_with_value",
        r"datum_system_with_associated_model_coordinate_system",
        r"plus_minus_toleranced_datum", r"upper_lower_toleranced_datum",
        r"directed_tolerance_zone", r"oriented_tolerance_zone",
        r"affected_plane_tolerance_zone", r"non_uniform_zone_definition",
        r"projected_zone_definition", r"runout_zone_definition",
        r"tolerance_zone_definition", r"tolerance_zone_with_datum",
        r"angularity_tolerance", r"circular_runout_tolerance",
        r"coaxiality_tolerance", r"concentricity_tolerance",
        r"cylindricity_tolerance", r"flatness_tolerance",
        r"line_profile_tolerance", r"parallelism_tolerance",
        r"perpendicularity_tolerance", r"position_tolerance",
        r"roundness_tolerance", r"straightness_tolerance",
        r"surface_profile_tolerance", r"symmetry_tolerance",
        r"total_runout_tolerance", r"dimension_and_tolerance_callouts",
        r"dimension_tolerance",
        r"model_based_3d_geometrical_dimensioning_and_tolerancing_representation",
        r"mechanical_design_requirement_item_association",
        r"requirement_view_definition",
        r"requirement_view_definition_relationship",
        r"requirement_assignment", r"requirement_satisfied_by",
        r"requirement_source", r"requirement_version",
        r"requirement_version_relationship",
        r"requirement_collection_relationship",
        r"requirement_precedence_relationship",
        r"single_requirement_view_definition",
        r"requirement_identification_and_version", r"requirement",
        r"test_specification", r"validation", r"certification",
        r"certification_assignment", r"geometric_validation_property",
        r"geometric_validation_property_representation",
        r"characteristic_data_column_header",
        r"characteristic_data_column_header_link",
        r"characteristic_data_table", r"characteristic_data_table_header",
        r"characteristic_data_table_header_decomposition",
        r"characteristic_data_table_header_usage",
        r"characteristic_data_table_representation",
        r"characteristic_data_table_row", r"value_range",
        r"value_range_with_global_unit", r"value_limit", r"value_list",
        r"value_set", r"value_with_tolerances", r"limits_and_fits",
        r"precision_qualifier", r"type_qualifier", r"uncertainty_qualifier",
        r"measure_qualification", r"qualified_representation_item",
        r"qualified_numerical_item_with_unit",
        r"qualified_tolerance_characteristic",
        r"maths_value_precision_qualifier", r"maths_value_qualification",
        r"maths_value_with_unit", r"number_of_decimal_places",
        r"significant_number_of_digits", r"expanded_uncertainty",
        r"standard_uncertainty", r"qualitative_uncertainty",
        r"uncertainty_with_unit", r"representation_with_uncertainty",
        r"measure_item_with_precision", r"measure_item",
        r"measure_representation", r"measurement_path",
        r"numerical_item_with_unit", r"numerical_item_with_global_unit",
        r"value_with_unit", r"value_with_tolerances",
    ]),
])


def _match(text, patterns):
    """返回 text 命中的全部类别标签。"""
    hits = []
    for label, pats in patterns.items():
        for p in pats:
            if re.search(p, text):
                hits.append(label)
                break
    return hits


def classify(name, module=""):
    """对单个 ARM 概念分类。

    :param name:   概念名（如 ``Machining_feature``）
    :param module: 所属模块名（如 ``machining_features``），可为空
    :return: ``{"industry": [...], "users": [...], "lifecycle": [...]}``
    """
    text = (name + " " + (module or "")).lower()
    return {
        "industry": _match(text, INDUSTRY),
        "users": _match(text, USERS),
        "lifecycle": _match(text, LIFECYCLE),
    }


if __name__ == "__main__":
    import json
    import os
    import collections as _c

    here = os.path.dirname(os.path.abspath(__file__))
    data = json.load(open(os.path.join(os.path.dirname(here), "arm_concepts.json"),
                          encoding="utf-8"))
    cs = [c for c in data["concepts"] if c["source"] == "ap242"]
    cnt = {"industry": _c.Counter(), "users": _c.Counter(), "lifecycle": _c.Counter()}
    unclassified = {"industry": 0, "users": 0, "lifecycle": 0}
    for c in cs:
        r = classify(c["name"], c["module"])
        for dim in cnt:
            if r[dim]:
                for lab in r[dim]:
                    cnt[dim][lab] += 1
            else:
                unclassified[dim] += 1
    for dim in ("industry", "users", "lifecycle"):
        print("==", dim, "==  (未分类 %d)" % unclassified[dim])
        for lab, n in cnt[dim].most_common():
            print("   %-28s %d" % (lab, n))
