# -*- coding: utf-8 -*-
"""STEP AIM 实体的领域分类。

提供两个正交的分类维度，每个实体可同时命中多个类别（多标签）：

* ``INDUSTRY``  —— 工业用途 / 工科分类（NC、机械、电力、渲染、几何、PMI …）
* ``SOFTWARE``  —— 软件模块 / 设计理念（2D 绘图、3D 建模、制图、草图、渲染 …）

用法::

    from domains import classify
    classify("b_spline_curve_with_knots")
    # -> {"industry": ["几何 / 拓扑 / 实体造型"], "software": ["3D 建模 / 实体造型"]}
"""
import collections
import re

# --------------------------------------------------------------------------
# 维度 A：工业用途 / 工科分类
# --------------------------------------------------------------------------
INDUSTRY = collections.OrderedDict([
    ("NC / 数控加工（CAM）", [
        r"machining", r"toolpath", r"workingstep", r"workplan", r"nc_function",
        r"milling", r"turning", r"drilling", r"boring", r"tapping", r"threading",
        r"grooving", r"facing", r"contouring", r"knurling", r"spindle",
        r"feed_speed", r"rapid_movement", r"dwell", r"touch_probing",
        r"adaptive_control", r"process_plan", r"process_operation", r"process_model",
        r"process_property", r"process_product", r"product_definition_process",
        r"property_process", r"fixture", r"cutting", r"tool_usage", r"tool_body",
        r"tool_direction", r"approach_retract", r"operator_instruction",
        r"machining_technology", r"workpiece", r"via_arc", r"via_helix",
        r"freeform", r"bottom_and_side", r"side_milling", r"plane_milling",
        r"back_boring", r"drilling_type", r"milling_type", r"turning_type",
        r"extended_type", r"additive_type", r"resource_requirement",
        r"requirement_for_action_resource", r"action_resource", r"resource_property",
        r"sequential_method", r"serial_action_method", r"concurrent_action_method",
    ]),
    ("机械 / 运动学 / 传动", [
        r"kinematic", r"_pair", r"mechanism", r"motion", r"joint", r"link",
        r"gear", r"rack", r"pinion", r"revolute", r"prismatic", r"rolling",
        r"sliding", r"homokinetic", r"universal", r"spherical_pair",
        r"planar_pair", r"cylindrical_pair", r"screw_pair", r"surface_pair",
        r"curve_pair", r"rigid_link", r"flexible_link", r"actuated",
        r"constrained_pair", r"unconstrained_pair", r"high_order", r"low_order",
        r"su_parameters", r"rotation_about_direction", r"prescribed_path",
        r"resulting_path", r"kinematic_analysis", r"kinematic_control",
    ]),
    ("电力 / 物理量 / 计量单位", [
        r"electric_", r"magnetic_", r"capacitance", r"conductance", r"inductance",
        r"resistance", r"charge", r"potential", r"current", r"power_",
        r"energy", r"force", r"pressure", r"temperature", r"thermal",
        r"thermodynamic", r"radioactivity", r"illuminance", r"luminous",
        r"absorbed_dose", r"dose_equivalent", r"frequency", r"acceleration",
        r"mass_", r"density", r"plane_angle", r"solid_angle", r"ratio_",
        r"measure_with_unit", r"_unit$", r"si_unit", r"named_unit",
        r"derived_unit", r"conversion_based_unit", r"context_dependent_unit",
        r"dimensional_exponents", r"global_unit_assigned_context",
        r"dielectric_constant", r"loss_tangent", r"hardness",
        r"amount_of_substance", r"celsius_temperature",
    ]),
    ("渲染 / 外观 / 可视化", [
        r"presentation", r"_style", r"colour", r"rendering", r"light_source",
        r"camera", r"reflectance", r"transparent", r"fill_area", r"hatching",
        r"hatch", r"tile", r"invisibility", r"hlhsr", r"view_volume",
        r"background", r"shaded", r"texture", r"marker", r"font", r"glyph",
        r"styled_item", r"over_riding_styled", r"surface_side_style",
        r"pre_defined_colour", r"pre_defined_curve_font", r"pre_defined_marker",
        r"pre_defined_tile", r"symbol_colour", r"symbol_style", r"text_style",
        r"curve_style", r"point_style", r"surface_style", r"fill_area_style",
        r"externally_defined_style", r"externally_defined_tile",
        r"externally_defined_hatch_style", r"externally_defined_curve_font",
        r"externally_defined_text_font", r"externally_defined_marker",
        r"externally_defined_terminator_symbol", r"externally_defined_colour",
        r"user_defined_marker", r"user_defined_terminator_symbol",
        r"user_defined_curve_font", r"solid_curve_font", r"vector_style",
        r"one_direction_repeat_factor", r"two_direction_repeat_factor",
        r"planar_box", r"planar_extent", r"presented_item", r"presentation_area",
        r"presentation_layer", r"presentation_set", r"presentation_size",
        r"presentation_view", r"presentation_representation",
        r"hidden_element_over_riding_styled_item",
    ]),
    ("几何 / 拓扑 / 实体造型", [
        r"geometry_schema", r"topology_schema", r"geometric_model",
        r"geometric_representation", r"geometric_set", r"geometric_curve_set",
        r"cartesian_point", r"cartesian_transformation", r"polar_point",
        r"cylindrical_point", r"spherical_point", r"point_on_", r"point_in_",
        r"point_replica", r"degenerate_pcurve", r"evaluated_degenerate_pcurve",
        r"direction", r"vector", r"placement", r"axis1_placement",
        r"axis2_placement", r"_curve", r"_surface", r"_solid", r"_shell",
        r"_face", r"_edge", r"_vertex", r"_loop", r"_wire", r"_volume",
        r"spline", r"bezier", r"conic", r"circle", r"ellipse", r"hyperbola",
        r"parabola", r"polyline", r"clothoid", r"involute", r"torus",
        r"cylinder", r"cone", r"sphere", r"pyramid", r"wedge", r"hexahedron",
        r"tetrahedron", r"block", r"brep", r"csg", r"manifold", r"half_space",
        r"boolean_result", r"swept", r"extruded", r"revolved", r"primitive",
        r"tessellated", r"triangulated", r"cyclide", r"ellipsoid",
        r"box_domain", r"boxed_half_space", r"convex_hexahedron",
        r"coordinates_list", r"repositioned_tessellated_item",
        r"surface_patch", r"composite_curve", r"trimmed_curve",
        r"offset_curve", r"offset_surface", r"oriented_surface",
        r"curve_replica", r"surface_replica", r"seam_curve",
        r"intersection_curve", r"boundary_curve", r"outer_boundary_curve",
        r"bounded_curve", r"bounded_surface", r"bounded_pcurve",
        r"bounded_surface_curve", r"pcurve", r"surface_curve",
        r"elementary_surface", r"elementary_brep", r"advanced_brep",
        r"advanced_face", r"faceted_brep", r"faceted_primitive",
        r"edge_based_wireframe", r"shell_based_wireframe",
        r"shell_based_surface_model", r"face_based_surface_model",
        r"geometrically_bounded", r"manifold_surface_shape_representation",
        r"non_manifold_surface_shape_representation",
        r"manifold_subsurface", r"curve_swept_solid", r"ruled_surface_swept",
        r"constructive_geometry", r"geometric_model_element_relationship",
        r"compound_shape_representation", r"compound_representation_item",
        r"geometric_item_specific_usage", r"chain_based_geometric_item_specific_usage",
    ]),
    ("公差 / 尺寸 / 基准（PMI）", [
        r"tolerance", r"datum", r"dimension", r"gps_", r"limits_and_fits",
        r"uncertainty", r"precision_qualifier", r"type_qualifier",
        r"measure_qualification", r"qualified_representation_item",
        r"qualified_measure", r"value_range", r"value_format_type_qualifier",
        r"maths_value_precision_qualifier", r"expanded_uncertainty",
        r"standard_uncertainty", r"qualitative_uncertainty",
        r"dimensional_characteristic", r"shape_dimension_representation",
        r"default_tolerance", r"surface_condition_callout",
        r"pre_defined_surface_condition_symbol", r"surface_texture_representation",
        r"contact_ratio_representation", r"tactile_appearance_representation",
        r"visual_appearance_representation", r"hardness_representation",
        r"feature_for_datum_target_relationship", r"placed_datum_target_feature",
        r"connection_zone_interface_plane_relationship",
        r"feature_definition_with_connection_area",
    ]),
    ("制图 / 标注 / 工程图", [
        r"draughting", r"annotation", r"callout", r"leader", r"terminator",
        r"projection_curve", r"text_literal", r"composite_text",
        r"text_string_representation", r"symbol_representation",
        r"symbol_target", r"subfigure", r"placeholder", r"dimension_curve",
        r"dimension_text_associativity", r"shape_aspect_associativity",
        r"annotation_occurrence_associativity", r"defined_symbol",
        r"pre_defined_symbol", r"defined_character_glyph",
        r"pre_defined_character_glyph", r"externally_defined_symbol",
        r"externally_defined_character_glyph", r"apll_point",
        r"auxiliary_leader_line", r"dimension_pair", r"angular_dimension",
        r"linear_dimension", r"ordinate_dimension", r"radius_dimension",
        r"diameter_dimension", r"curve_dimension", r"leader_directed_dimension",
        r"structured_dimension_callout", r"dimension_callout",
        r"geometrical_tolerance_callout", r"draughting_model",
        r"mechanical_design_and_draughting", r"model_geometric_view",
        r"default_model_geometric_view", r"pmi_requirement_item_association",
        r"mechanical_design_requirement_item_association",
        r"dimension_curve_terminator_to_projection_curve_associativity",
    ]),
    ("产品 / 配置 / 数据管理（PDM）", [
        r"product_", r"configuration", r"approval", r"certification", r"contract",
        r"document", r"effectivity", r"organization", r"person", r"security",
        r"action", r"date", r"time_interval", r"calendar", r"ordinal_date",
        r"year_month", r"local_time", r"event_occurrence", r"group",
        r"classification", r"requirement", r"information_right", r"retention",
        r"work_order", r"work_request", r"project", r"version", r"revision",
        r"breakdown", r"assembly_component_usage", r"next_assembly",
        r"occurrence", r"substitute", r"promissory_usage",
        r"make_from_usage_option", r"specified_higher_usage",
        r"multi_level_reference_designator", r"quantified_assembly",
        r"alternate_product_relationship", r"product_definition",
        r"product_concept", r"product_class", r"concept_feature",
        r"characterized_product_concept_feature", r"package_product_concept_feature",
        r"inclusion_product_concept_feature", r"exclusive_product_concept_feature",
        r"product_identification", r"product_specification",
        r"specification_definition", r"document_identifier",
        r"applied_", r"attribute_classification", r"external_identification",
        r"identification_assignment", r"name_assignment", r"group_assignment",
        r"organizational_project", r"person_and_organization",
        r"security_classification", r"effectivity_assignment",
        r"configured_effectivity", r"class_usage_effectivity",
        r"instance_usage_context_assignment", r"known_source",
        r"external_class_library", r"externally_defined_class",
        r"characterized_class", r"class_system", r"class_by_extension",
        r"class_by_intension", r"single_property_is_definition",
        r"requirement_view_definition_relationship", r"assigned_requirement",
        r"requirement_assigned_object", r"requirement_assignment",
        r"requirement_source", r"satisfied_requirement", r"satisfies_requirement",
        r"satisfying_item", r"source_for_requirement", r"sourced_requirement",
        r"functional_breakdown", r"functional_element_usage",
        r"physical_breakdown", r"physical_element_usage",
        r"breakdown_element", r"breakdown_context", r"breakdown_of",
        r"product_definition_element_relationship",
        r"product_definition_group_assignment",
        r"applied_usage_right", r"information_usage_right",
        r"right_to_usage_association", r"usage_association",
        r"multi_language_attribute_assignment", r"attribute_language_assignment",
        r"partial_document_with_structured_text_representation_assignment",
        r"document_product_equivalence", r"applied_document_reference",
        r"applied_document_usage_constraint_assignment",
        r"included_text_block", r"structured_text_composition",
        r"structured_text_representation", r"tagged_text_format",
        r"tagged_text_item", r"uniform_resource_identifier",
        r"document_file", r"retention",
    ]),
    ("表达式 / 数学 / 矩阵", [
        r"expression", r"_function", r"maths_", r"literal", r"variable",
        r"operator", r"interval", r"tuple", r"array", r"matrix", r"complex_number",
        r"integral", r"derivative", r"table_function", r"_space$",
        r"elementary_space", r"finite_space", r"function_space",
        r"listed_product_space", r"uniform_product_space", r"extended_tuple_space",
        r"listed_data", r"listed_integer_data", r"listed_real_data",
        r"listed_string_data", r"listed_logical_data", r"listed_complex_number_data",
        r"externally_listed_data", r"mathematical_description",
        r"dependent_variable_definition", r"bound_variable_semantics",
        r"free_variable_semantics", r"variable_semantics", r"environment",
        r"banded_matrix", r"basic_sparse_matrix", r"symmetric_matrix",
        r"symmetric_banded_matrix", r"triangular_matrix", r"strict_triangular_matrix",
        r"repackaging_function", r"reindexed_array_function",
        r"rationalize_function", r"b_spline_basis", r"b_spline_function",
        r"imported_curve_function", r"imported_point_function",
        r"imported_surface_function", r"imported_volume_function",
        r"parallel_composed_function", r"series_composed_function",
        r"selector_function", r"restriction_function", r"format_function",
        r"explicit_table_function", r"linearized_table_function",
        r"regular_table_function", r"standard_table_function",
        r"expression_denoted_function", r"application_defined_function",
        r"abstracted_expression_function", r"constant_function",
        r"definite_integral_function", r"finite_function", r"general_linear_function",
        r"homogeneous_linear_function", r"partial_derivative_function",
        r"value_function", r"int_value_function", r"length_function",
        r"maximum_function", r"minimum_function", r"minus_function",
        r"odd_function", r"square_root_function", r"abs_function",
        r"acos_function", r"asin_function", r"atan_function", r"cos_function",
        r"sin_function", r"tan_function", r"exp_function", r"log_function",
        r"log2_function", r"log10_function", r"boolean_defined_function",
        r"integer_defined_function", r"numeric_defined_function",
        r"real_defined_function", r"string_defined_function",
        r"sql_mappable_defined_function", r"defined_function",
        r"function_application", r"binary_function_call", r"unary_function_call",
        r"multiple_arity_function_call", r"expression_item_representation_item",
        r"expression_representation_item", r"numeric_variable",
    ]),
    ("增材制造（AM）", [
        r"additive_manufacturing", r"additive_type_operation",
        r"additive_manufacturing_atom", r"additive_manufacturing_construction",
        r"additive_manufacturing_feature",
    ]),
    ("扫描 / 点云 / 逆向", [
        r"scan_", r"scanner_", r"point_cloud", r"scanned_data",
        r"triangulated_point_cloud_dataset",
    ]),
    ("材料 / 表面条件", [
        r"material_", r"general_material", r"surface_conditions",
        r"surface_texture", r"tactile_appearance", r"visual_appearance",
        r"contact_ratio", r"hardness", r"data_environment",
        r"material_property_representation", r"material_designation",
    ]),
    ("特征 / 加工特征", [
        r"feature", r"boss", r"pocket", r"slot", r"hole", r"chamfer", r"fillet",
        r"rib_", r"protrusion", r"step$", r"taper", r"thread", r"pattern",
        r"profile", r"counterbore", r"countersink", r"counterdrill", r"spotface",
        r"round_hole", r"edge_round", r"outer_round", r"turned_knurl",
        r"removal_volume", r"replicate_feature", r"compound_feature",
        r"transition_feature", r"applied_area", r"flat_face", r"spherical_cap",
        r"rounded_end", r"marking", r"shape_defining_relationship",
        r"feature_component", r"feature_pattern", r"modified_pattern",
        r"pattern_offset_membership", r"pattern_omit_membership",
        r"instanced_feature", r"placed_feature", r"general_feature",
        r"shape_feature_definition", r"shape_feature_definition_element_relationship",
        r"shape_feature_definition_relationship", r"composite_unit_shape_aspect",
        r"composite_shape_aspect", r"composite_group_shape_aspect",
        r"constituent_shape_aspect", r"shape_aspect_occurrence",
        r"shape_aspect_relationship", r"shape_aspect_deriving_relationship",
        r"derived_shape_aspect", r"apex", r"centre_of_symmetry",
        r"contacting_feature", r"continuous_shape_aspect", r"extension",
        r"geometric_alignment", r"geometric_contact", r"geometric_intersection",
        r"parallel_offset", r"perpendicular_to", r"tangent",
        r"symmetric_shape_aspect", r"between_shape_aspect",
        r"all_around_shape_aspect", r"shape_representation_with_parameters",
        r"direction_shape_representation", r"face_shape_representation",
        r"location_shape_representation", r"path_shape_representation",
        r"planar_shape_representation", r"block_shape_representation",
        r"cylindrical_shape_representation", r"ngon_shape_representation",
        r"face_shape_representation_relationship",
    ]),
])

# --------------------------------------------------------------------------
# 维度 B：软件模块 / 设计理念
# --------------------------------------------------------------------------
SOFTWARE = collections.OrderedDict([
    ("2D 绘图 / 草图（2D drafting & sketch）", [
        r"_2d", r"planar_", r"two_direction", r"profile", r"closed_profile",
        r"open_path_profile", r"linear_profile", r"partial_circular_profile",
        r"ngon_closed_profile", r"rectangular_closed_profile",
        r"rounded_u_profile", r"square_u_profile", r"vee_profile",
        r"tee_profile", r"revolved_profile", r"path_feature_component",
        r"annotation_plane", r"planar_box", r"planar_extent",
        r"axis2_placement_2d", r"cartesian_transformation_operator_2d",
        r"offset_curve_2d", r"curve_dimension", r"angular_dimension",
        r"linear_dimension", r"ordinate_dimension", r"radius_dimension",
        r"diameter_dimension", r"dimension_pair", r"dimension_curve",
        r"draughting", r"annotation", r"text_literal", r"composite_text",
        r"symbol_representation", r"symbol_target", r"subfigure",
        r"placeholder", r"leader", r"terminator", r"callout",
        r"projection_curve", r"apll_point", r"auxiliary_leader_line",
        r"pre_defined_dimension_symbol", r"pre_defined_geometrical_tolerance_symbol",
        r"pre_defined_surface_condition_symbol", r"pre_defined_terminator_symbol",
        r"pre_defined_point_marker_symbol", r"user_defined_terminator_symbol",
        r"externally_defined_terminator_symbol", r"defined_symbol",
        r"pre_defined_symbol", r"defined_character_glyph",
        r"pre_defined_character_glyph", r"externally_defined_symbol",
        r"externally_defined_character_glyph", r"text_style",
        r"text_string_representation", r"draughting_model",
        r"draughting_elements", r"dimension_callout",
        r"structured_dimension_callout", r"dimension_text_associativity",
        r"shape_aspect_associativity", r"annotation_occurrence_associativity",
        r"dimension_curve_terminator_to_projection_curve_associativity",
        r"dimension_callout_component_relationship",
        r"dimension_callout_relationship", r"leader_directed_dimension",
        r"leader_directed_callout", r"dimension_curve_directed_callout",
        r"projection_directed_callout", r"draughting_callout",
        r"draughting_callout_relationship", r"draughting_model_item_association",
        r"draughting_model_item_association_with_placeholder",
        r"annotation_placeholder_leader_line",
        r"annotation_placeholder_occurrence_with_leader_line",
        r"annotation_placeholder_occurrence",
        r"annotation_to_annotation_leader_line",
        r"annotation_to_model_leader_line", r"annotation_curve_occurrence",
        r"annotation_fill_area", r"annotation_fill_area_occurrence",
        r"annotation_occurrence", r"annotation_occurrence_relationship",
        r"annotation_point_occurrence", r"annotation_symbol",
        r"annotation_symbol_occurrence", r"annotation_text",
        r"annotation_text_occurrence", r"annotation_subfigure_occurrence",
        r"draughting_annotation_occurrence", r"draughting_subfigure_representation",
        r"draughting_symbol_representation",
        r"draughting_text_literal_with_delineation",
        r"tessellated_annotation_occurrence", r"composite_text_with_",
        r"text_literal_with_", r"dimension_curve_terminator",
        r"geometrical_tolerance_callout", r"datum_feature_callout",
        r"datum_target_callout", r"surface_condition_callout",
        r"dimension_tolerance", r"externally_defined_dimension_definition",
        r"mechanical_design_and_draughting",
        r"mechanical_design_presentation_representation_with_draughting",
        r"mechanical_design_geometric_presentation",
        r"mechanical_design_shaded_presentation",
        r"mechanical_design_requirement_item_association",
        r"pmi_requirement_item_association", r"model_geometric_view",
        r"default_model_geometric_view", r"draughting_pre_defined_colour",
        r"draughting_pre_defined_text_font", r"draughting_pre_defined_curve_font",
    ]),
    ("3D 建模 / 实体造型（3D modeling & solid）", [
        r"_3d", r"solid", r"brep", r"csg", r"manifold", r"shell", r"volume",
        r"half_space", r"boolean_result", r"swept", r"extruded", r"revolved",
        r"primitive", r"block", r"sphere", r"torus", r"cone", r"cylinder",
        r"pyramid", r"wedge", r"hexahedron", r"tetrahedron", r"tessellated",
        r"triangulated", r"cyclide", r"ellipsoid", r"box_domain",
        r"boxed_half_space", r"convex_hexahedron", r"coordinates_list",
        r"repositioned_tessellated_item", r"surface_patch", r"composite_curve",
        r"trimmed_curve", r"offset_curve", r"offset_surface", r"oriented_surface",
        r"curve_replica", r"surface_replica", r"seam_curve", r"intersection_curve",
        r"boundary_curve", r"outer_boundary_curve", r"bounded_curve",
        r"bounded_surface", r"bounded_pcurve", r"bounded_surface_curve", r"pcurve",
        r"surface_curve", r"elementary_surface", r"spline", r"bezier", r"conic",
        r"circle", r"ellipse", r"hyperbola", r"parabola", r"polyline",
        r"clothoid", r"involute", r"cartesian_point", r"cartesian_transformation",
        r"polar_point", r"cylindrical_point", r"spherical_point", r"point_on_",
        r"point_in_", r"point_replica", r"degenerate_pcurve",
        r"evaluated_degenerate_pcurve", r"direction", r"vector", r"placement",
        r"axis1_placement", r"axis2_placement_3d", r"_curve", r"_surface",
        r"_shell", r"_face", r"_edge", r"_vertex", r"_loop", r"_wire",
        r"geometric_set", r"geometric_curve_set", r"geometric_representation",
        r"advanced_face", r"faceted_primitive", r"edge_based_wireframe",
        r"shell_based_wireframe", r"shell_based_surface_model",
        r"face_based_surface_model", r"geometrically_bounded",
        r"manifold_surface_shape_representation",
        r"non_manifold_surface_shape_representation", r"manifold_subsurface",
        r"curve_swept_solid", r"ruled_surface_swept", r"constructive_geometry",
        r"geometric_model_element_relationship", r"compound_shape_representation",
        r"geometric_item_specific_usage",
        r"chain_based_geometric_item_specific_usage", r"surface_curve_swept",
        r"fixed_reference_swept", r"surface_of_linear_extrusion",
        r"surface_of_revolution", r"rectangular_trimmed_surface",
        r"curve_bounded_surface", r"rectangular_composite_surface",
        r"locally_refined_spline", r"local_b_spline", r"b_spline",
        r"quasi_uniform", r"uniform_curve", r"uniform_surface", r"uniform_volume",
        r"rational_b_spline", r"rational_locally_refined",
        r"cubic_bezier_tessellated_edge", r"cubic_bezier_triangulated_face",
        r"cubic_tessellated_connecting_edge", r"tessellated_connecting_edge",
        r"complex_triangulated_face", r"complex_triangulated_surface_set",
        r"triangulated_surface_set", r"tessellated_surface_set",
        r"tessellated_curve_set", r"tessellated_point_set",
        r"tessellated_geometric_set", r"tessellated_structured_item",
        r"tessellated_shape_representation", r"tessellated_item",
        r"tessellated_shell", r"tessellated_solid", r"tessellated_wire",
        r"tessellated_vertex", r"tessellated_edge", r"tessellated_face",
        r"styled_tessellated_item_with_colours", r"reparametrised_composite_curve_segment",
        r"composite_curve_segment", r"composite_curve_on_surface",
        r"surface_curve_swept_area_solid", r"extruded_area_solid",
        r"revolved_area_solid", r"swept_area_solid", r"swept_disk_solid",
        r"swept_face_solid", r"extruded_face_solid", r"revolved_face_solid",
        r"brep_with_voids", r"solid_replica", r"solid_model",
        r"eccentric_cone", r"cyclide_segment_solid", r"rectangular_pyramid",
        r"right_angular_wedge", r"right_circular_cone",
        r"right_circular_cylinder", r"block_volume", r"wedge_volume",
        r"pyramid_volume", r"tetrahedron_volume", r"hexahedron_volume",
        r"spherical_volume", r"cylindrical_volume", r"eccentric_conical_volume",
        r"toroidal_volume", r"ellipsoid_volume", r"b_spline_volume",
        r"bezier_volume", r"quasi_uniform_volume", r"uniform_volume",
        r"rational_b_spline_volume", r"locally_refined_spline_volume",
        r"rational_locally_refined_spline_volume", r"point_in_volume",
        r"volume_with_faces", r"volume_with_parametric_boundary",
        r"volume_with_shell", r"connected_volume_set", r"connected_volume_sub_set",
        r"closed_shell", r"open_shell", r"oriented_closed_shell",
        r"oriented_open_shell", r"vertex_shell", r"wire_shell",
        r"connected_face_set", r"connected_face_sub_set", r"connected_edge_set",
        r"connected_edge_sub_set", r"edge_curve", r"edge_loop", r"face_bound",
        r"face_outer_bound", r"face_surface", r"vertex_loop", r"vertex_point",
        r"poly_loop", r"seam_edge", r"subedge", r"subface", r"subpath",
        r"oriented_edge", r"oriented_face", r"oriented_path", r"open_path",
        r"topological_representation_item", r"geometric_representation_context",
        r"geometric_representation_item",
    ]),
    ("制图 / 工程图（drawing & annotation）", [
        r"draughting", r"annotation", r"callout", r"leader", r"terminator",
        r"projection_curve", r"text_literal", r"composite_text",
        r"text_string_representation", r"symbol_representation", r"symbol_target",
        r"subfigure", r"placeholder", r"dimension_curve",
        r"dimension_text_associativity", r"shape_aspect_associativity",
        r"annotation_occurrence_associativity", r"defined_symbol",
        r"pre_defined_symbol", r"defined_character_glyph",
        r"pre_defined_character_glyph", r"externally_defined_symbol",
        r"externally_defined_character_glyph", r"apll_point",
        r"auxiliary_leader_line", r"dimension_pair", r"angular_dimension",
        r"linear_dimension", r"ordinate_dimension", r"radius_dimension",
        r"diameter_dimension", r"curve_dimension", r"leader_directed_dimension",
        r"structured_dimension_callout", r"dimension_callout",
        r"geometrical_tolerance_callout", r"draughting_model",
        r"mechanical_design_and_draughting", r"model_geometric_view",
        r"default_model_geometric_view", r"pmi_requirement_item_association",
        r"mechanical_design_requirement_item_association",
        r"dimension_curve_terminator_to_projection_curve_associativity",
        r"datum_feature_callout", r"datum_target_callout",
        r"surface_condition_callout", r"pre_defined_dimension_symbol",
        r"pre_defined_geometrical_tolerance_symbol",
        r"pre_defined_surface_condition_symbol", r"dimension_tolerance",
        r"externally_defined_dimension_definition",
        r"mechanical_design_presentation_representation_with_draughting",
        r"mechanical_design_geometric_presentation",
        r"mechanical_design_shaded_presentation",
        r"draughting_pre_defined_colour", r"draughting_pre_defined_text_font",
        r"draughting_pre_defined_curve_font", r"draughting_elements",
        r"dimension_callout_component_relationship",
        r"dimension_callout_relationship", r"leader_directed_callout",
        r"dimension_curve_directed_callout", r"projection_directed_callout",
        r"draughting_callout", r"draughting_callout_relationship",
        r"draughting_model_item_association",
        r"draughting_model_item_association_with_placeholder",
        r"annotation_placeholder_leader_line",
        r"annotation_placeholder_occurrence_with_leader_line",
        r"annotation_placeholder_occurrence",
        r"annotation_to_annotation_leader_line",
        r"annotation_to_model_leader_line", r"annotation_curve_occurrence",
        r"annotation_fill_area", r"annotation_fill_area_occurrence",
        r"annotation_occurrence", r"annotation_occurrence_relationship",
        r"annotation_point_occurrence", r"annotation_symbol",
        r"annotation_symbol_occurrence", r"annotation_text",
        r"annotation_text_occurrence", r"annotation_subfigure_occurrence",
        r"draughting_annotation_occurrence", r"draughting_subfigure_representation",
        r"draughting_symbol_representation",
        r"draughting_text_literal_with_delineation",
        r"tessellated_annotation_occurrence", r"composite_text_with_",
        r"text_literal_with_", r"dimension_curve_terminator",
        r"dimension_curve_terminator_to_projection_curve_associativity",
    ]),
    ("渲染 / 可视化（rendering & visualization）", [
        r"presentation", r"_style", r"colour", r"rendering", r"light_source",
        r"camera", r"reflectance", r"transparent", r"fill_area", r"hatching",
        r"hatch", r"tile", r"invisibility", r"hlhsr", r"view_volume",
        r"background", r"shaded", r"texture", r"marker", r"font", r"glyph",
        r"styled_item", r"over_riding_styled", r"surface_side_style",
        r"pre_defined_colour", r"pre_defined_curve_font", r"pre_defined_marker",
        r"pre_defined_tile", r"symbol_colour", r"symbol_style", r"text_style",
        r"curve_style", r"point_style", r"surface_style", r"fill_area_style",
        r"externally_defined_style", r"externally_defined_tile",
        r"externally_defined_hatch_style", r"externally_defined_curve_font",
        r"externally_defined_text_font", r"externally_defined_marker",
        r"externally_defined_colour", r"user_defined_marker",
        r"user_defined_curve_font", r"solid_curve_font", r"vector_style",
        r"one_direction_repeat_factor", r"two_direction_repeat_factor",
        r"presented_item", r"presentation_area", r"presentation_layer",
        r"presentation_set", r"presentation_size", r"presentation_view",
        r"presentation_representation", r"hidden_element_over_riding_styled_item",
        r"context_dependent_invisibility", r"context_dependent_over_riding_styled_item",
        r"surface_rendering_properties", r"surface_style_rendering",
        r"surface_style_rendering_with_properties", r"surface_style_transparent",
        r"surface_style_reflectance", r"surface_style_fill_area",
        r"surface_style_boundary", r"surface_style_control_grid",
        r"surface_style_parameter_line", r"surface_style_segmentation_curve",
        r"surface_style_silhouette", r"surface_style_usage",
        r"pre_defined_surface_side_style", r"fill_area_style_colour",
        r"fill_area_style_hatching", r"fill_area_style_tile",
        r"fill_area_style_tiles", r"character_glyph_style_outline",
        r"character_glyph_style_stroke", r"curve_style_font",
        r"curve_style_font_and_scaling", r"curve_style_font_pattern",
        r"curve_style_rendering", r"text_style_for_defined_font",
        r"text_style_with_box_characteristics", r"text_style_with_mirror",
        r"text_style_with_spacing", r"camera_image", r"camera_model",
        r"camera_usage", r"light_source_ambient", r"light_source_directional",
        r"light_source_positional", r"light_source_spot",
        r"camera_model_with_light_sources", r"camera_model_d3",
        r"camera_model_d3_multi_clipping", r"camera_model_d3_with_hlhsr",
        r"camera_image_3d_with_scale", r"area_in_set", r"background_colour",
        r"presentation_style_assignment", r"presentation_style_by_context",
        r"presentation_organization_schema", r"presentation_resource_schema",
        r"presentation_appearance_schema", r"presentation_definition_schema",
        r"presentation_hierarchy_mim", r"applied_presented_item",
        r"colour_rgb", r"colour_specification", r"planar_box", r"planar_extent",
    ]),
    ("装配 / 结构（assembly & structure）", [
        r"assembly", r"product_definition_usage", r"next_assembly",
        r"occurrence", r"component", r"breakdown", r"structure",
        r"alternate_product_relationship", r"substitute", r"promissory_usage",
        r"make_from_usage_option", r"specified_higher_usage",
        r"multi_level_reference_designator", r"quantified_assembly",
        r"product_definition_occurrence", r"product_definition_specified_occurrence",
        r"product_definition_element_relationship",
        r"product_definition_group_assignment", r"breakdown_element",
        r"breakdown_context", r"breakdown_of", r"functional_breakdown",
        r"functional_element_usage", r"physical_breakdown",
        r"physical_element_usage", r"definitional_product_definition_usage",
        r"product_definition_relationship", r"product_definition_formation",
        r"product_definition_reference", r"generic_product_definition_reference",
        r"product_definition_context", r"product_definition_effectivity",
        r"product_definition_substitute", r"product_definition_with_associated_documents",
        r"product_related_product_category", r"product_category",
        r"product_relationship", r"product_definition_shape",
        r"product_definition_kinematics", r"product_definition_relationship_kinematics",
        r"product_definition_resource", r"product_definition_formation_resource",
        r"product_process_plan", r"product_resource", r"product_as_planned",
        r"product_design_to_individual", r"product_design_version_to_individual",
        r"product_planned_to_realized", r"product_identification",
        r"product_specification", r"product_concept", r"product_class",
        r"product_context", r"product_concept_context", r"product$",
    ]),
    ("运动学 / 仿真（kinematics & simulation）", [
        r"kinematic", r"_pair", r"mechanism", r"motion", r"joint", r"link",
        r"gear", r"rack", r"pinion", r"revolute", r"prismatic", r"rolling",
        r"sliding", r"homokinetic", r"universal", r"spherical_pair",
        r"planar_pair", r"cylindrical_pair", r"screw_pair", r"surface_pair",
        r"curve_pair", r"rigid_link", r"flexible_link", r"actuated",
        r"constrained_pair", r"unconstrained_pair", r"high_order", r"low_order",
        r"su_parameters", r"rotation_about_direction", r"prescribed_path",
        r"resulting_path", r"kinematic_analysis", r"kinematic_control",
        r"interpolated_configuration", r"path_node", r"path_parameter",
        r"point_to_point_path", r"linear_path", r"circular_path",
        r"curve_based_path", r"item_link_motion_relationship",
        r"link_motion_relationship", r"link_motion_transformation",
        r"link_motion_representation_along_path", r"kinematic_path",
        r"kinematic_path_segment", r"kinematic_path_defined_by_curves",
        r"kinematic_path_defined_by_nodes", r"geometric_representation_context_with_parameter",
        r"kinematic_link_representation", r"kinematic_link_representation_association",
        r"pair_representation_relationship", r"kinematic_property",
        r"context_dependent_kinematic_link_representation",
        r"kinematic_property_definition_representation",
        r"kinematic_property_mechanism_representation",
        r"kinematic_property_topology_representation",
        r"kinematic_topology", r"oriented_joint", r"kinematic_loop",
        r"kinematic_joint", r"kinematic_link", r"mechanism_state_representation",
        r"mechanism_representation", r"pair_value", r"rotation_about_direction",
    ]),
    ("制造 / 工艺规划（CAM & process planning）", [
        r"machining", r"toolpath", r"workingstep", r"workplan", r"nc_function",
        r"milling", r"turning", r"drilling", r"boring", r"tapping", r"threading",
        r"grooving", r"facing", r"contouring", r"knurling", r"spindle",
        r"feed_speed", r"rapid_movement", r"dwell", r"touch_probing",
        r"adaptive_control", r"process_plan", r"process_operation", r"process_model",
        r"process_property", r"process_product", r"product_definition_process",
        r"property_process", r"fixture", r"cutting", r"tool_usage", r"tool_body",
        r"tool_direction", r"approach_retract", r"operator_instruction",
        r"machining_technology", r"workpiece", r"via_arc", r"via_helix",
        r"freeform", r"bottom_and_side", r"side_milling", r"plane_milling",
        r"back_boring", r"drilling_type", r"milling_type", r"turning_type",
        r"extended_type", r"additive_type", r"resource_requirement",
        r"requirement_for_action_resource", r"action_resource", r"resource_property",
        r"sequential_method", r"serial_action_method", r"concurrent_action_method",
        r"additive_manufacturing", r"additive_manufacturing_atom",
        r"additive_manufacturing_construction", r"additive_manufacturing_feature",
        r"additive_manufacturing_setup", r"additive_manufacturing_build_plate",
        r"additive_manufacturing_support_structure",
    ]),
    ("检测 / PMI（inspection & tolerance）", [
        r"tolerance", r"datum", r"dimension", r"gps_", r"limits_and_fits",
        r"uncertainty", r"precision_qualifier", r"type_qualifier",
        r"measure_qualification", r"qualified_representation_item",
        r"qualified_measure", r"value_range", r"value_format_type_qualifier",
        r"maths_value_precision_qualifier", r"expanded_uncertainty",
        r"standard_uncertainty", r"qualitative_uncertainty",
        r"dimensional_characteristic", r"shape_dimension_representation",
        r"default_tolerance", r"surface_condition_callout",
        r"pre_defined_surface_condition_symbol", r"surface_texture_representation",
        r"contact_ratio_representation", r"tactile_appearance_representation",
        r"visual_appearance_representation", r"hardness_representation",
        r"feature_for_datum_target_relationship", r"placed_datum_target_feature",
        r"connection_zone_interface_plane_relationship",
        r"feature_definition_with_connection_area", r"measure_with_unit",
        r"measure_representation_item", r"descriptive_representation_item",
        r"global_uncertainty_assigned_context", r"uncertainty_assigned_representation",
        r"uncertainty_measure_with_unit", r"value_representation_item",
        r"shape_representation_with_parameters", r"dimensional_location",
        r"dimensional_size", r"angular_location", r"angular_size",
        r"directed_dimensional_location", r"dimensional_location_with_path",
        r"dimensional_size_with_path", r"dimensional_location_with_datum_feature",
        r"dimensional_size_with_datum_feature",
    ]),
    ("数据管理 / 配置（PDM & configuration）", [
        r"product_", r"configuration", r"approval", r"certification", r"contract",
        r"document", r"effectivity", r"organization", r"person", r"security",
        r"action", r"date", r"time_interval", r"calendar", r"ordinal_date",
        r"year_month", r"local_time", r"event_occurrence", r"group",
        r"classification", r"requirement", r"information_right", r"retention",
        r"work_order", r"work_request", r"project", r"version", r"revision",
        r"breakdown", r"assembly_component_usage", r"next_assembly",
        r"occurrence", r"substitute", r"promissory_usage",
        r"make_from_usage_option", r"specified_higher_usage",
        r"multi_level_reference_designator", r"quantified_assembly",
        r"alternate_product_relationship", r"product_definition",
        r"product_concept", r"product_class", r"concept_feature",
        r"characterized_product_concept_feature", r"package_product_concept_feature",
        r"inclusion_product_concept_feature", r"exclusive_product_concept_feature",
        r"product_identification", r"product_specification",
        r"specification_definition", r"document_identifier",
        r"applied_", r"attribute_classification", r"external_identification",
        r"identification_assignment", r"name_assignment", r"group_assignment",
        r"organizational_project", r"person_and_organization",
        r"security_classification", r"effectivity_assignment",
        r"configured_effectivity", r"class_usage_effectivity",
        r"instance_usage_context_assignment", r"known_source",
        r"external_class_library", r"externally_defined_class",
        r"characterized_class", r"class_system", r"class_by_extension",
        r"class_by_intension", r"single_property_is_definition",
        r"requirement_view_definition_relationship", r"assigned_requirement",
        r"requirement_assigned_object", r"requirement_assignment",
        r"requirement_source", r"satisfied_requirement", r"satisfies_requirement",
        r"satisfying_item", r"source_for_requirement", r"sourced_requirement",
        r"functional_breakdown", r"functional_element_usage",
        r"physical_breakdown", r"physical_element_usage",
        r"breakdown_element", r"breakdown_context", r"breakdown_of",
        r"product_definition_element_relationship",
        r"product_definition_group_assignment",
        r"applied_usage_right", r"information_usage_right",
        r"right_to_usage_association", r"usage_association",
        r"multi_language_attribute_assignment", r"attribute_language_assignment",
        r"partial_document_with_structured_text_representation_assignment",
        r"document_product_equivalence", r"applied_document_reference",
        r"applied_document_usage_constraint_assignment",
        r"included_text_block", r"structured_text_composition",
        r"structured_text_representation", r"tagged_text_format",
        r"tagged_text_item", r"uniform_resource_identifier",
        r"document_file", r"retention", r"language",
    ]),
    ("元模型 / 表示框架（representation framework）", [
        r"representation", r"_item$", r"_context$", r"mapped_item",
        r"definitional_", r"founded_item", r"representation_map",
        r"representation_relationship", r"representation_context",
        r"representation_reference", r"representation_context_reference",
        r"compound_representation_item", r"value_representation_item",
        r"measure_representation_item", r"descriptive_representation_item",
        r"null_representation_item", r"row_representation_item",
        r"table_representation_item", r"boolean_representation_item",
        r"date_representation_item", r"date_time_representation_item",
        r"integer_representation_item", r"logical_representation_item",
        r"rational_representation_item", r"real_representation_item",
        r"expression_representation_item", r"expression_item_representation_item",
        r"characteristic_data_column_header", r"characteristic_data_table_header",
        r"characteristic_type", r"range_characteristic",
        r"characteristic_data_column_header_link",
        r"characteristic_data_table_header_decomposition",
        r"functionally_defined_transformation", r"item_defined_transformation",
        r"parametric_representation_context", r"global_uncertainty_assigned_context",
        r"uncertainty_assigned_representation", r"characterized_representation",
        r"characterized_item_within_representation",
        r"item_identified_representation_usage",
        r"chain_based_item_identified_representation_usage",
        r"context_dependent_shape_representation",
        r"property_definition_representation", r"shape_definition_representation",
        r"shape_representation", r"shape_representation_reference",
        r"shape_representation_relationship", r"compound_shape_representation",
        r"externally_defined_representation", r"externally_defined_representation_item",
        r"externally_defined_string",
        r"externally_defined_representation_with_parameters",
        r"representation_item_relationship", r"definitional_representation",
        r"definitional_representation_relationship",
        r"definitional_representation_relationship_with_same_context",
        r"representation_schema", r"basic_data_representation_mim",
        r"characterized_representation_mim", r"extended_measure_representation_mim",
        r"systems_engineering_representation_schema",
    ]),
    ("类型系统 / 选择机制（type system & select）", [
        r"_or_", r"select", r"enumeration", r"enumerators",
    ]),
    ("外部引用 / 代理机制（external reference & proxy）", [
        r"externally_defined", r"external_", r"proxy", r"placeholder",
        r"pre_defined", r"_reference", r"known_source", r"external_source",
        r"external_class_library", r"externally_defined_class",
        r"externally_listed_data", r"external_identification",
        r"applied_external_identification_assignment",
        r"applied_external_identification_assignment_relationship",
        r"external_properties_mim", r"externally_defined_general_property",
        r"external_representation_item_mim", r"external_item_identification_assignment_mim",
        r"external_reference_schema", r"incomplete_data_reference_mechanism_mim",
        r"idrm_classification_assignment", r"plib_class_reference_mim",
    ]),
    ("属性 / 特征化（property & characterization）", [
        r"property", r"characterized_", r"_characteristic", r"qualified_",
        r"general_property", r"material_property", r"action_property",
        r"resource_property", r"process_property", r"property_definition",
        r"property_definition_relationship", r"property_definition_representation",
        r"general_property_association", r"general_property_relationship",
        r"characterized_object", r"characterized_object_relationship",
        r"characterized_item_within_representation", r"characterized_representation",
        r"characterized_class", r"characterized_product_concept_feature",
        r"characteristic_data_column_header", r"characteristic_data_table_header",
        r"characteristic_type", r"range_characteristic",
        r"shape_property_assignment_mim", r"generic_material_aspects_mim",
        r"general_material_property", r"property_as_definition_mim",
        r"single_property_is_definition", r"external_properties_mim",
        r"externally_defined_general_property", r"action_property_representation",
        r"resource_property_representation", r"material_property_representation",
        r"data_environment", r"qualified_representation_item",
        r"qualified_measure", r"measure_qualification", r"type_qualifier",
        r"precision_qualifier", r"value_format_type_qualifier",
        r"maths_value_precision_qualifier", r"descriptive_representation_item",
        r"measure_representation_item", r"value_representation_item",
    ]),
    ("有效性 / 版本（effectivity & versioning）", [
        r"effectivity", r"_version", r"_revision", r"_formation",
        r"dated_effectivity", r"lot_effectivity", r"serial_numbered_effectivity",
        r"time_interval_based_effectivity", r"configuration_effectivity",
        r"product_definition_effectivity", r"effectivity_relationship",
        r"effectivity_assignment", r"effectivity_context_assignment",
        r"effectivity_context_role", r"applied_effectivity_assignment",
        r"applied_ineffectivity_assignment", r"configured_effectivity_assignment",
        r"configured_effectivity_context_assignment",
        r"class_usage_effectivity_context_assignment",
        r"instance_usage_context_assignment", r"effectivity_application_mim",
        r"specification_based_configuration_mim", r"specification_control_mim",
        r"configuration_item_revision_sequence", r"versioned_action_request",
        r"versioned_action_request_relationship", r"product_definition_formation",
        r"product_definition_formation_relationship",
        r"product_definition_formation_with_specified_source",
        r"product_definition_formation_resource",
    ]),
])


# --------------------------------------------------------------------------
# 维度 C：产品生命周期「功能环节」分类
# --------------------------------------------------------------------------
# 按实体在产品生命周期中所处的功能环节归类：
#   CAD（设计 / 建模）→ CAE（分析 / 仿真）→ CAPP（工艺规划）→ CAM（制造 / 加工）
#   → CMM（检测 / 计量）→ PDM（数据管理）；工程图贯穿设计—制造—检测全过程。
LIFECYCLE = collections.OrderedDict([
    ("CAD（设计 / 建模 / 实体造型）", [
        r"_3d", r"solid", r"brep", r"csg", r"manifold", r"shell", r"volume",
        r"half_space", r"boolean_result", r"swept", r"extruded", r"revolved",
        r"primitive", r"block", r"sphere", r"torus", r"cone", r"cylinder",
        r"pyramid", r"wedge", r"hexahedron", r"tetrahedron", r"tessellated",
        r"triangulated", r"cyclide", r"ellipsoid", r"box_domain",
        r"boxed_half_space", r"convex_hexahedron", r"coordinates_list",
        r"repositioned_tessellated_item", r"surface_patch", r"composite_curve",
        r"trimmed_curve", r"offset_curve", r"offset_surface", r"oriented_surface",
        r"curve_replica", r"surface_replica", r"seam_curve", r"intersection_curve",
        r"boundary_curve", r"outer_boundary_curve", r"bounded_curve",
        r"bounded_surface", r"bounded_pcurve", r"bounded_surface_curve", r"pcurve",
        r"surface_curve", r"elementary_surface", r"spline", r"bezier", r"conic",
        r"circle", r"ellipse", r"hyperbola", r"parabola", r"polyline",
        r"clothoid", r"involute", r"cartesian_point", r"cartesian_transformation",
        r"polar_point", r"cylindrical_point", r"spherical_point", r"point_on_",
        r"point_in_", r"point_replica", r"degenerate_pcurve",
        r"evaluated_degenerate_pcurve", r"direction", r"vector", r"placement",
        r"axis1_placement", r"axis2_placement_3d", r"_curve", r"_surface",
        r"_shell", r"_face", r"_edge", r"_vertex", r"_loop", r"_wire",
        r"geometric_set", r"geometric_curve_set", r"geometric_representation",
        r"advanced_face", r"faceted_primitive", r"edge_based_wireframe",
        r"shell_based_wireframe", r"shell_based_surface_model",
        r"face_based_surface_model", r"geometrically_bounded",
        r"manifold_surface_shape_representation",
        r"non_manifold_surface_shape_representation", r"manifold_subsurface",
        r"curve_swept_solid", r"ruled_surface_swept", r"constructive_geometry",
        r"geometric_model_element_relationship", r"compound_shape_representation",
        r"geometric_item_specific_usage",
        r"chain_based_geometric_item_specific_usage", r"surface_curve_swept",
        r"fixed_reference_swept", r"surface_of_linear_extrusion",
        r"surface_of_revolution", r"rectangular_trimmed_surface",
        r"curve_bounded_surface", r"rectangular_composite_surface",
        r"locally_refined_spline", r"local_b_spline", r"b_spline",
        r"quasi_uniform", r"uniform_curve", r"uniform_surface", r"uniform_volume",
        r"rational_b_spline", r"rational_locally_refined",
        r"cubic_bezier_tessellated_edge", r"cubic_bezier_triangulated_face",
        r"cubic_tessellated_connecting_edge", r"tessellated_connecting_edge",
        r"complex_triangulated_face", r"complex_triangulated_surface_set",
        r"triangulated_surface_set", r"tessellated_surface_set",
        r"tessellated_curve_set", r"tessellated_point_set",
        r"tessellated_geometric_set", r"tessellated_structured_item",
        r"tessellated_shape_representation", r"tessellated_item",
        r"tessellated_shell", r"tessellated_solid", r"tessellated_wire",
        r"tessellated_vertex", r"tessellated_edge", r"tessellated_face",
        r"styled_tessellated_item_with_colours",
        r"reparametrised_composite_curve_segment", r"composite_curve_segment",
        r"composite_curve_on_surface", r"surface_curve_swept_area_solid",
        r"extruded_area_solid", r"revolved_area_solid", r"swept_area_solid",
        r"swept_disk_solid", r"swept_face_solid", r"extruded_face_solid",
        r"revolved_face_solid", r"brep_with_voids", r"solid_replica",
        r"solid_model", r"eccentric_cone", r"cyclide_segment_solid",
        r"rectangular_pyramid", r"right_angular_wedge", r"right_circular_cone",
        r"right_circular_cylinder", r"block_volume", r"wedge_volume",
        r"pyramid_volume", r"tetrahedron_volume", r"hexahedron_volume",
        r"spherical_volume", r"cylindrical_volume", r"eccentric_conical_volume",
        r"toroidal_volume", r"ellipsoid_volume", r"b_spline_volume",
        r"bezier_volume", r"quasi_uniform_volume", r"rational_b_spline_volume",
        r"locally_refined_spline_volume", r"rational_locally_refined_spline_volume",
        r"point_in_volume", r"volume_with_faces", r"volume_with_parametric_boundary",
        r"volume_with_shell", r"connected_volume_set", r"connected_volume_sub_set",
        r"closed_shell", r"open_shell", r"oriented_closed_shell",
        r"oriented_open_shell", r"vertex_shell", r"wire_shell",
        r"connected_face_set", r"connected_face_sub_set", r"connected_edge_set",
        r"connected_edge_sub_set", r"edge_curve", r"edge_loop", r"face_bound",
        r"face_outer_bound", r"face_surface", r"vertex_loop", r"vertex_point",
        r"poly_loop", r"seam_edge", r"subedge", r"subface", r"subpath",
        r"oriented_edge", r"oriented_face", r"oriented_path", r"open_path",
        r"topological_representation_item", r"geometric_representation_context",
        r"geometric_representation_item", r"shape_representation",
        r"shape_aspect", r"feature", r"profile", r"sketch", r"wireframe",
        r"topolog", r"geometr", r"parametric", r"trimmed", r"offset", r"blend",
        r"fillet", r"chamfer", r"draft", r"thickness", r"cross_section",
        r"silhouette", r"mapped_item", r"representation",
        r"_hole", r"hole_", r"boss", r"pocket", r"slot", r"_pattern",
        r"edge_round", r"spherical_cap", r"toroidal_", r"conical_",
        r"cylindrical_", r"transition", r"apex", r"extension", r"rib",
        r"stud", r"knurl", r"groove", r"recess", r"undercut", r"counterbore",
        r"countersink", r"counterdrill", r"round_hole", r"feature_",
    ]),
    ("CAM（制造 / 加工 / 数控）", [
        r"machining", r"toolpath", r"workingstep", r"workplan", r"nc_function",
        r"milling", r"turning", r"drilling", r"boring", r"tapping", r"threading",
        r"grooving", r"facing", r"contouring", r"knurling", r"spindle",
        r"feed_speed", r"rapid_movement", r"dwell", r"touch_probing",
        r"adaptive_control", r"cutting", r"tool_usage", r"tool_body",
        r"tool_direction", r"approach_retract", r"operator_instruction",
        r"machining_technology", r"workpiece", r"via_arc", r"via_helix",
        r"freeform", r"bottom_and_side", r"side_milling", r"plane_milling",
        r"back_boring", r"drilling_type", r"milling_type", r"turning_type",
        r"extended_type", r"additive_type", r"additive_manufacturing",
        r"additive_manufacturing_atom", r"additive_manufacturing_construction",
        r"additive_manufacturing_feature", r"additive_manufacturing_setup",
        r"additive_manufacturing_build_plate",
        r"additive_manufacturing_support_structure", r"fixture",
        r"manufacturing_feature", r"machining_feature", r"feature_definition",
        r"tool_", r"machine_", r"cnc", r"nc_",
    ]),
    ("CAE（分析 / 仿真 / 运动学）", [
        r"kinematic", r"_pair", r"mechanism", r"motion", r"joint", r"link",
        r"gear", r"rack", r"pinion", r"revolute", r"prismatic", r"rolling",
        r"sliding", r"homokinetic", r"universal", r"spherical_pair",
        r"planar_pair", r"cylindrical_pair", r"screw_pair", r"surface_pair",
        r"curve_pair", r"rigid_link", r"flexible_link", r"actuated",
        r"constrained_pair", r"unconstrained_pair", r"high_order", r"low_order",
        r"su_parameters", r"rotation_about_direction", r"prescribed_path",
        r"resulting_path", r"kinematic_analysis", r"kinematic_control",
        r"interpolated_configuration", r"path_node", r"path_parameter",
        r"point_to_point_path", r"linear_path", r"circular_path",
        r"curve_based_path", r"item_link_motion_relationship",
        r"link_motion_relationship", r"link_motion_transformation",
        r"link_motion_representation_along_path", r"kinematic_path",
        r"kinematic_path_segment", r"kinematic_path_defined_by_curves",
        r"kinematic_path_defined_by_nodes",
        r"geometric_representation_context_with_parameter",
        r"kinematic_link_representation", r"kinematic_link_representation_association",
        r"pair_representation_relationship", r"kinematic_property",
        r"context_dependent_kinematic_link_representation",
        r"kinematic_property_definition_representation",
        r"kinematic_property_mechanism_representation",
        r"kinematic_property_topology_representation", r"kinematic_topology",
        r"oriented_joint", r"kinematic_loop", r"kinematic_joint",
        r"kinematic_link", r"mechanism_state_representation",
        r"mechanism_representation", r"pair_value", r"analysis", r"simulation",
        r"finite_element", r"boundary_condition", r"stress", r"strain",
        r"displacement", r"modal", r"thermal_analysis", r"optimization",
    ]),
    ("CAPP（工艺规划 / 工序 / 资源）", [
        r"process_plan", r"process_operation", r"process_model",
        r"process_property", r"process_product", r"product_definition_process",
        r"property_process", r"process_specification", r"workplan",
        r"workingstep", r"operation", r"production", r"routing", r"sequence",
        r"sequential_method", r"serial_action_method", r"concurrent_action_method",
        r"resource_requirement", r"requirement_for_action_resource",
        r"action_resource", r"resource_property", r"resource_", r"schedule",
        r"lead_time", r"setup", r"work_order", r"work_request", r"action_",
        r"method", r"time_", r"date", r"calendar", r"event_occurrence",
    ]),
    ("PDM（产品数据管理 / 配置）", [
        r"product_", r"configuration", r"approval", r"certification", r"contract",
        r"document", r"effectivity", r"organization", r"person", r"security",
        r"group", r"classification", r"requirement", r"information_right",
        r"retention", r"project", r"version", r"revision", r"breakdown",
        r"assembly_component_usage", r"next_assembly", r"occurrence", r"substitute",
        r"promissory_usage", r"make_from_usage_option", r"specified_higher_usage",
        r"multi_level_reference_designator", r"quantified_assembly",
        r"alternate_product_relationship", r"product_definition",
        r"product_concept", r"product_class", r"concept_feature",
        r"characterized_product_concept_feature", r"package_product_concept_feature",
        r"inclusion_product_concept_feature", r"exclusive_product_concept_feature",
        r"product_identification", r"product_specification",
        r"specification_definition", r"document_identifier", r"applied_",
        r"attribute_classification", r"external_identification",
        r"identification_assignment", r"name_assignment", r"group_assignment",
        r"organizational_project", r"person_and_organization",
        r"security_classification", r"effectivity_assignment",
        r"configured_effectivity", r"class_usage_effectivity",
        r"instance_usage_context_assignment", r"known_source",
        r"external_class_library", r"externally_defined_class",
        r"characterized_class", r"class_system", r"class_by_extension",
        r"class_by_intension", r"single_property_is_definition",
        r"requirement_view_definition_relationship", r"assigned_requirement",
        r"requirement_assigned_object", r"requirement_assignment",
        r"requirement_source", r"satisfied_requirement", r"satisfies_requirement",
        r"satisfying_item", r"source_for_requirement", r"sourced_requirement",
        r"functional_breakdown", r"functional_element_usage",
        r"physical_breakdown", r"physical_element_usage", r"breakdown_element",
        r"breakdown_context", r"breakdown_of",
        r"product_definition_element_relationship",
        r"product_definition_group_assignment", r"applied_usage_right",
        r"information_usage_right", r"right_to_usage_association",
        r"usage_association", r"multi_language_attribute_assignment",
        r"attribute_language_assignment",
        r"partial_document_with_structured_text_representation_assignment",
        r"document_product_equivalence", r"applied_document_reference",
        r"applied_document_usage_constraint_assignment", r"included_text_block",
        r"structured_text_composition", r"structured_text_representation",
        r"tagged_text_format", r"tagged_text_item", r"uniform_resource_identifier",
        r"document_file", r"language", r"assembly", r"structure",
    ]),
    ("CMM（检测 / 计量 / PMI）", [
        r"tolerance", r"datum", r"dimension", r"gps_", r"limits_and_fits",
        r"uncertainty", r"precision_qualifier", r"type_qualifier",
        r"measure_qualification", r"qualified_representation_item",
        r"qualified_measure", r"value_range", r"value_format_type_qualifier",
        r"maths_value_precision_qualifier", r"expanded_uncertainty",
        r"standard_uncertainty", r"qualitative_uncertainty",
        r"dimensional_characteristic", r"shape_dimension_representation",
        r"default_tolerance", r"surface_condition_callout",
        r"pre_defined_surface_condition_symbol", r"surface_texture_representation",
        r"contact_ratio_representation", r"tactile_appearance_representation",
        r"visual_appearance_representation", r"hardness_representation",
        r"feature_for_datum_target_relationship", r"placed_datum_target_feature",
        r"connection_zone_interface_plane_relationship",
        r"feature_definition_with_connection_area", r"measure_with_unit",
        r"measure_representation_item", r"descriptive_representation_item",
        r"global_uncertainty_assigned_context", r"uncertainty_assigned_representation",
        r"uncertainty_measure_with_unit", r"value_representation_item",
        r"shape_representation_with_parameters", r"dimensional_location",
        r"dimensional_size", r"angular_location", r"angular_size",
        r"directed_dimensional_location", r"dimensional_location_with_path",
        r"dimensional_size_with_path", r"dimensional_location_with_datum_feature",
        r"dimensional_size_with_datum_feature", r"inspection", r"measurement",
        r"probe", r"coordinate_measuring", r"cmm", r"calibration",
        r"verification", r"validation", r"quality", r"geometric_tolerance",
        r"tolerance_zone", r"runout", r"flatness", r"straightness", r"roundness",
        r"cylindricity", r"parallelism", r"perpendicularity", r"angularity",
        r"concentricity", r"symmetry", r"position_tolerance",
    ]),
    ("工程图（制图 / 标注 / 图纸）", [
        r"draughting", r"drawing", r"annotation", r"callout", r"leader",
        r"terminator", r"projection_curve", r"text_literal", r"composite_text",
        r"text_string_representation", r"symbol_representation", r"symbol_target",
        r"subfigure", r"placeholder", r"dimension_curve",
        r"dimension_text_associativity", r"shape_aspect_associativity",
        r"annotation_occurrence_associativity", r"defined_symbol",
        r"pre_defined_symbol", r"defined_character_glyph",
        r"pre_defined_character_glyph", r"externally_defined_symbol",
        r"externally_defined_character_glyph", r"apll_point",
        r"auxiliary_leader_line", r"dimension_pair", r"angular_dimension",
        r"linear_dimension", r"ordinate_dimension", r"radius_dimension",
        r"diameter_dimension", r"curve_dimension", r"leader_directed_dimension",
        r"structured_dimension_callout", r"dimension_callout",
        r"geometrical_tolerance_callout", r"draughting_model",
        r"mechanical_design_and_draughting", r"model_geometric_view",
        r"default_model_geometric_view", r"pmi_requirement_item_association",
        r"mechanical_design_requirement_item_association",
        r"dimension_curve_terminator_to_projection_curve_associativity",
        r"datum_feature_callout", r"datum_target_callout",
        r"surface_condition_callout", r"pre_defined_dimension_symbol",
        r"pre_defined_geometrical_tolerance_symbol",
        r"pre_defined_surface_condition_symbol", r"dimension_tolerance",
        r"externally_defined_dimension_definition",
        r"mechanical_design_presentation_representation_with_draughting",
        r"mechanical_design_geometric_presentation",
        r"mechanical_design_shaded_presentation",
        r"draughting_pre_defined_colour", r"draughting_pre_defined_text_font",
        r"draughting_pre_defined_curve_font", r"draughting_elements",
        r"dimension_callout_component_relationship",
        r"dimension_callout_relationship", r"leader_directed_callout",
        r"dimension_curve_directed_callout", r"projection_directed_callout",
        r"draughting_callout", r"draughting_callout_relationship",
        r"draughting_model_item_association",
        r"draughting_model_item_association_with_placeholder",
        r"annotation_placeholder_leader_line",
        r"annotation_placeholder_occurrence_with_leader_line",
        r"annotation_placeholder_occurrence",
        r"annotation_to_annotation_leader_line",
        r"annotation_to_model_leader_line", r"annotation_curve_occurrence",
        r"annotation_fill_area", r"annotation_fill_area_occurrence",
        r"annotation_occurrence", r"annotation_occurrence_relationship",
        r"annotation_point_occurrence", r"annotation_symbol",
        r"annotation_symbol_occurrence", r"annotation_text",
        r"annotation_text_occurrence", r"annotation_subfigure_occurrence",
        r"draughting_annotation_occurrence",
        r"draughting_subfigure_representation",
        r"draughting_symbol_representation",
        r"draughting_text_literal_with_delineation",
        r"tessellated_annotation_occurrence", r"composite_text_with_",
        r"text_literal_with_", r"dimension_curve_terminator", r"view_",
        r"presentation_view", r"section_", r"detail_", r"title_block",
        r"drawing_sheet", r"drawing_revision", r"drawing_frame",
        r"presentation", r"_style", r"colour", r"color", r"rendering",
        r"light_source", r"camera", r"reflectance", r"transparent",
        r"fill_area", r"hatching", r"hatch", r"tile", r"invisibility",
        r"hlhsr", r"view_volume", r"background", r"shaded", r"texture",
        r"marker", r"font", r"glyph", r"styled_item", r"over_riding_styled",
        r"surface_side_style", r"pre_defined_colour", r"pre_defined_curve_font",
        r"pre_defined_marker", r"pre_defined_tile", r"symbol_colour",
        r"symbol_style", r"text_style", r"curve_style", r"point_style",
        r"surface_style", r"fill_area_style", r"externally_defined_style",
        r"externally_defined_tile", r"externally_defined_hatch_style",
        r"externally_defined_curve_font", r"externally_defined_text_font",
        r"externally_defined_marker", r"externally_defined_colour",
        r"user_defined_marker", r"user_defined_curve_font", r"solid_curve_font",
        r"vector_style", r"one_direction_repeat_factor",
        r"two_direction_repeat_factor", r"presented_item", r"presentation_area",
        r"presentation_layer", r"presentation_set", r"presentation_size",
        r"presentation_representation",
        r"hidden_element_over_riding_styled_item",
        r"context_dependent_invisibility",
        r"context_dependent_over_riding_styled_item",
        r"surface_rendering_properties", r"surface_style_rendering",
        r"surface_style_rendering_with_properties", r"surface_style_transparent",
        r"surface_style_reflectance", r"surface_style_fill_area",
        r"surface_style_boundary", r"surface_style_control_grid",
        r"surface_style_parameter_line", r"surface_style_segmentation_curve",
        r"surface_style_silhouette", r"surface_style_usage",
        r"pre_defined_surface_side_style", r"fill_area_style_colour",
        r"fill_area_style_hatching", r"fill_area_style_tile",
        r"fill_area_style_tiles", r"character_glyph_style_outline",
        r"character_glyph_style_stroke", r"curve_style_font",
        r"curve_style_font_and_scaling", r"curve_style_font_pattern",
        r"curve_style_rendering", r"text_style_for_defined_font",
        r"text_style_with_box_characteristics", r"text_style_with_mirror",
        r"text_style_with_spacing", r"camera_image", r"camera_model",
        r"camera_usage", r"light_source_ambient", r"light_source_directional",
        r"light_source_positional", r"light_source_spot",
        r"camera_model_with_light_sources", r"camera_model_d3",
        r"camera_model_d3_multi_clipping", r"camera_model_d3_with_hlhsr",
        r"camera_image_3d_with_scale", r"area_in_set", r"background_colour",
        r"presentation_style_assignment", r"presentation_style_by_context",
        r"presentation_organization_schema", r"presentation_resource_schema",
        r"presentation_appearance_schema", r"presentation_definition_schema",
        r"presentation_hierarchy_mim", r"applied_presented_item",
        r"colour_rgb", r"colour_specification", r"planar_box", r"planar_extent",
    ]),
])


# --------------------------------------------------------------------------
# 精确名补充表：正则难以覆盖的零散实体，按名字精确归类
# --------------------------------------------------------------------------
EXTRA_INDUSTRY = {
    "几何 / 拓扑 / 实体造型": {
        "curve", "line", "point", "plane", "edge", "face", "face_bound",
        "face_outer_bound", "loop", "path", "open_path", "oriented_path",
        "subedge", "subface", "subpath", "solid_model", "solid_replica",
        "founded_item", "mapped_item", "functionally_defined_transformation",
        "item_defined_transformation", "application_context",
        "application_context_element", "application_protocol_definition",
        "product", "shape_aspect", "final_solution",
    },
    "公差 / 尺寸 / 基准（PMI）": {
        "angular_location", "angular_size", "non_uniform_zone_definition",
        "runout_zone_definition", "runout_zone_orientation",
    },
    "产品 / 配置 / 数据管理（PDM）": {
        "address", "aggregate_id_attribute", "attribute_value_assignment",
        "attribute_value_role", "characteristic_data_column_header",
        "characteristic_data_table_header",
        "characteristic_data_table_header_decomposition", "characteristic_type",
        "characterized_object", "characterized_object_relationship", "class",
        "configurable_item", "description_attribute", "external_source",
        "external_source_relationship", "externally_defined_general_property",
        "externally_defined_item", "externally_defined_item_relationship",
        "externally_defined_item_with_multiple_references",
        "externally_defined_string", "general_property",
        "general_property_association", "general_property_relationship",
        "id_attribute", "identification_role", "language", "name_attribute",
        "object_role", "pre_defined_item", "property_definition",
        "property_definition_relationship", "range_characteristic",
        "role_association",
    },
    "机械 / 运动学 / 传动": {
        "circular_path", "curve_based_path",
        "curve_based_path_with_orientation",
        "curve_based_path_with_orientation_and_parameters", "linear_path",
        "pair_value", "path_node", "point_to_point_path",
    },
    "表达式 / 数学 / 矩阵": {
        "comparison_equal", "comparison_greater", "comparison_greater_equal",
        "comparison_less", "comparison_less_equal", "comparison_not_equal",
    },
}

EXTRA_SOFTWARE = {
    "2D 绘图 / 草图（2D drafting & sketch）": {
        "curve", "line", "point", "plane", "edge", "face", "face_bound",
        "face_outer_bound", "loop", "path", "open_path", "oriented_path",
        "subedge", "subface", "subpath", "solid_model", "solid_replica",
        "founded_item", "mapped_item", "functionally_defined_transformation",
        "item_defined_transformation", "application_context",
        "application_context_element", "application_protocol_definition",
        "product", "shape_aspect", "final_solution", "address",
        "aggregate_id_attribute", "attribute_value_assignment",
        "attribute_value_role", "characteristic_data_column_header",
        "characteristic_data_table_header",
        "characteristic_data_table_header_decomposition", "characteristic_type",
        "characterized_object", "characterized_object_relationship", "class",
        "configurable_item", "description_attribute", "external_source",
        "external_source_relationship", "externally_defined_general_property",
        "externally_defined_item", "externally_defined_item_relationship",
        "externally_defined_item_with_multiple_references",
        "externally_defined_string", "general_property",
        "general_property_association", "general_property_relationship",
        "id_attribute", "identification_role", "language", "name_attribute",
        "object_role", "pre_defined_item", "property_definition",
        "property_definition_relationship", "range_characteristic",
        "role_association", "angular_location", "angular_size",
        "non_uniform_zone_definition", "runout_zone_definition",
        "runout_zone_orientation", "circular_path", "curve_based_path",
        "curve_based_path_with_orientation",
        "curve_based_path_with_orientation_and_parameters", "linear_path",
        "pair_value", "path_node", "point_to_point_path", "comparison_equal",
        "comparison_greater", "comparison_greater_equal", "comparison_less",
        "comparison_less_equal", "comparison_not_equal",
    },
    "3D 建模 / 实体造型（3D modeling & solid）": {
        "curve", "line", "point", "plane", "edge", "face", "face_bound",
        "face_outer_bound", "loop", "path", "open_path", "oriented_path",
        "subedge", "subface", "subpath", "solid_model", "solid_replica",
        "founded_item", "mapped_item", "functionally_defined_transformation",
        "item_defined_transformation", "application_context",
        "application_context_element", "application_protocol_definition",
        "product", "shape_aspect", "final_solution",
    },
    "制图 / 工程图（drawing & annotation）": {
        "angular_location", "angular_size", "non_uniform_zone_definition",
        "runout_zone_definition", "runout_zone_orientation",
    },
    "检测 / PMI（inspection & tolerance）": {
        "angular_location", "angular_size", "non_uniform_zone_definition",
        "runout_zone_definition", "runout_zone_orientation",
    },
    "运动学 / 仿真（kinematics & simulation）": {
        "circular_path", "curve_based_path",
        "curve_based_path_with_orientation",
        "curve_based_path_with_orientation_and_parameters", "linear_path",
        "pair_value", "path_node", "point_to_point_path",
    },
    "数据管理 / 配置（PDM & configuration）": {
        "address", "aggregate_id_attribute", "attribute_value_assignment",
        "attribute_value_role", "characteristic_data_column_header",
        "characteristic_data_table_header",
        "characteristic_data_table_header_decomposition", "characteristic_type",
        "characterized_object", "characterized_object_relationship", "class",
        "configurable_item", "description_attribute", "external_source",
        "external_source_relationship", "externally_defined_general_property",
        "externally_defined_item", "externally_defined_item_relationship",
        "externally_defined_item_with_multiple_references",
        "externally_defined_string", "general_property",
        "general_property_association", "general_property_relationship",
        "id_attribute", "identification_role", "language", "name_attribute",
        "object_role", "pre_defined_item", "property_definition",
        "property_definition_relationship", "range_characteristic",
        "role_association", "application_context",
        "application_context_element", "application_protocol_definition",
        "product", "final_solution",
    },
    "元模型 / 表示框架（representation framework）": {
        "founded_item", "mapped_item", "functionally_defined_transformation",
        "item_defined_transformation", "shape_aspect",
    },
    "属性 / 特征化（property & characterization）": {
        "characteristic_data_column_header", "characteristic_data_table_header",
        "characteristic_data_table_header_decomposition", "characteristic_type",
        "characterized_object", "characterized_object_relationship",
        "general_property", "general_property_association",
        "general_property_relationship", "property_definition",
        "property_definition_relationship", "range_characteristic",
        "externally_defined_general_property",
    },
    "外部引用 / 代理机制（external reference & proxy）": {
        "external_source", "external_source_relationship",
        "externally_defined_item", "externally_defined_item_relationship",
        "externally_defined_item_with_multiple_references",
        "externally_defined_string", "pre_defined_item",
    },
    "表达式 / 数学 / 矩阵": {
        "comparison_equal", "comparison_greater", "comparison_greater_equal",
        "comparison_less", "comparison_less_equal", "comparison_not_equal",
    },
    "类型系统 / 选择机制（type system & select）": {
        "class", "characteristic_type", "range_characteristic",
    },
}


# 生命周期「功能环节」精确名补充表
EXTRA_LIFECYCLE = {
    "CAD（设计 / 建模 / 实体造型）": {
        "curve", "line", "point", "plane", "edge", "face", "face_bound",
        "face_outer_bound", "loop", "path", "open_path", "oriented_path",
        "subedge", "subface", "subpath", "solid_model", "solid_replica",
        "founded_item", "mapped_item", "functionally_defined_transformation",
        "item_defined_transformation", "shape_aspect", "final_solution",
    },
    "CAM（制造 / 加工 / 数控）": {
        "circular_path", "curve_based_path",
        "curve_based_path_with_orientation",
        "curve_based_path_with_orientation_and_parameters", "linear_path",
        "pair_value", "path_node", "point_to_point_path",
    },
    "CAE（分析 / 仿真 / 运动学）": {
        "circular_path", "curve_based_path",
        "curve_based_path_with_orientation",
        "curve_based_path_with_orientation_and_parameters", "linear_path",
        "pair_value", "path_node", "point_to_point_path",
    },
    "CAPP（工艺规划 / 工序 / 资源）": {
        "comparison_equal", "comparison_greater", "comparison_greater_equal",
        "comparison_less", "comparison_less_equal", "comparison_not_equal",
    },
    "PDM（产品数据管理 / 配置）": {
        "address", "aggregate_id_attribute", "attribute_value_assignment",
        "attribute_value_role", "characteristic_data_column_header",
        "characteristic_data_table_header",
        "characteristic_data_table_header_decomposition", "characteristic_type",
        "characterized_object", "characterized_object_relationship", "class",
        "configurable_item", "description_attribute", "external_source",
        "external_source_relationship", "externally_defined_general_property",
        "externally_defined_item", "externally_defined_item_relationship",
        "externally_defined_item_with_multiple_references",
        "externally_defined_string", "general_property",
        "general_property_association", "general_property_relationship",
        "id_attribute", "identification_role", "language", "name_attribute",
        "object_role", "pre_defined_item", "property_definition",
        "property_definition_relationship", "range_characteristic",
        "role_association", "application_context",
        "application_context_element", "application_protocol_definition",
        "product", "final_solution",
    },
    "CMM（检测 / 计量 / PMI）": {
        "angular_location", "angular_size", "non_uniform_zone_definition",
        "runout_zone_definition", "runout_zone_orientation",
    },
    "工程图（制图 / 标注 / 图纸）": {
        "angular_location", "angular_size", "non_uniform_zone_definition",
        "runout_zone_definition", "runout_zone_orientation",
    },
}


def _match(name, patterns):
    for p in patterns:
        if re.search(p, name):
            return True
    return False


def industry_of(name):
    out = [k for k, pats in INDUSTRY.items() if _match(name, pats)]
    for k, names in EXTRA_INDUSTRY.items():
        if name in names and k not in out:
            out.append(k)
    if not out:
        out = ["其他 / 通用基础"]
    return out


def software_of(name):
    out = [k for k, pats in SOFTWARE.items() if _match(name, pats)]
    for k, names in EXTRA_SOFTWARE.items():
        if name in names and k not in out:
            out.append(k)
    if not out:
        out = ["其他 / 通用基础"]
    return out


def lifecycle_of(name):
    out = [k for k, pats in LIFECYCLE.items() if _match(name, pats)]
    for k, names in EXTRA_LIFECYCLE.items():
        if name in names and k not in out:
            out.append(k)
    if not out:
        out = ["通用 / 基础"]
    return out


def classify(name, dash_kind=None):
    """返回 ``{"industry": [...], "software": [...], "lifecycle": [...]}``。

    ``dash_kind`` 为 ``"DEFINED TYPE"`` / ``"SELECT"`` 时，会补上类型系统标签。
    """
    ind = industry_of(name)
    sw = software_of(name)
    lc = lifecycle_of(name)
    if dash_kind in ("SELECT", "DEFINED TYPE"):
        tag = "类型系统 / 选择机制（type system & select）"
        if tag not in sw:
            sw.append(tag)
    return {"industry": ind, "software": sw, "lifecycle": lc}


if __name__ == "__main__":
    import json
    import os
    import sys

    here = os.path.dirname(os.path.abspath(__file__))
    data = json.load(open(os.path.join(os.path.dirname(here), "aim_entities.json"),
                          encoding="utf-8"))
    names = sorted({e["name"] for e in data["entities"]})
    miss_i = [n for n in names if not industry_of(n)]
    miss_s = [n for n in names if not software_of(n)]
    miss_l = [n for n in names if not lifecycle_of(n)]
    print("实体总数:", len(names))
    print("未命中工业用途:", len(miss_i))
    print("未命中软件模块:", len(miss_s))
    print("未命中功能环节:", len(miss_l))
    print("--- 未命中工业用途示例 ---")
    print(", ".join(miss_i[:80]))
    print("--- 未命中软件模块示例 ---")
    print(", ".join(miss_s[:80]))
    print("--- 未命中功能环节示例 ---")
    print(", ".join(miss_l[:80]))
