# -*- coding: utf-8 -*-
"""STEP AIM 实体名词术语表：token -> 中文。用于自动组合中文名称。"""

TOKENS = {
    "2d": "二维", "3d": "三维", "about": "关于", "abs": "绝对值", "absorbed": "吸收",
    "abstracted": "抽象", "acceleration": "加速度", "accuracy": "精度", "acos": "反余弦",
    "action": "动作", "actuated": "受驱动", "adaptive": "自适应", "additive": "增材",
    "address": "地址", "advanced": "高级", "aggregate": "聚合", "alignment": "对齐",
    "all": "全部", "along": "沿", "alternate": "交替", "ambient": "环境", "amount": "数量",
    "analysis": "分析", "and": "与", "angle": "角", "angular": "角度", "angularity": "倾斜度",
    "annotation": "标注", "apex": "顶点", "apll": "APLL", "appearance": "外观",
    "application": "应用", "applied": "应用", "approach": "接近", "approval": "批准",
    "arc": "圆弧", "area": "面积", "arity": "元数", "around": "绕", "array": "数组",
    "as": "作为", "asin": "反正弦", "aspect": "要素", "assembly": "装配",
    "assigned": "赋值", "assignment": "赋值", "associated": "关联", "association": "关联",
    "associativity": "关联性", "atan": "反正切", "atom": "原子", "attribute": "属性",
    "auxiliary": "辅助", "axis1": "轴1", "axis2": "轴2", "b": "B", "back": "后",
    "background": "背景", "banded": "带状", "based": "基于", "basic": "基本", "basis": "基",
    "between": "介于", "bezier": "贝塞尔", "binary": "二进制", "blanking": "冲裁",
    "block": "块", "body": "体", "boolean": "布尔", "boring": "镗孔", "boss": "凸台",
    "bottom": "底部", "bound": "界", "boundary": "边界", "bounded": "有界",
    "bounds": "边界", "box": "盒", "boxed": "盒式", "branch": "分支", "breakdown": "分解",
    "brep": "边界表示", "build": "构建", "by": "按", "calendar": "日历", "call": "调用",
    "callout": "注记", "camera": "相机", "cap": "盖", "capacitance": "电容",
    "cartesian": "笛卡儿", "category": "类别", "cell": "单元", "celsius": "摄氏度",
    "centre": "中心", "certification": "认证", "chain": "链", "chamfer": "倒角",
    "character": "字符", "characteristic": "特征", "characteristics": "特性",
    "characterization": "特征化", "characterized": "特征化", "charge": "电荷",
    "circle": "圆", "circular": "圆形", "class": "类", "classification": "分类",
    "clipping": "裁剪", "closed": "闭合", "clothoid": "回旋曲线", "cloud": "点云",
    "coaxiality": "同轴度", "colour": "颜色", "coloured": "着色", "colours": "颜色",
    "column": "列", "common": "公共", "comparison": "比较", "compartment": "格",
    "complex": "复合", "component": "组件", "composed": "组合", "composite": "组合",
    "composition": "组成", "compound": "复合", "concat": "连接", "concentricity": "同轴度",
    "concept": "概念", "concurrent": "并发", "condition": "条件", "conditional": "条件",
    "conductance": "电导", "cone": "圆锥", "configurable": "可配置",
    "configuration": "配置", "configured": "已配置", "conic": "二次曲线",
    "conical": "圆锥面", "connected": "连接", "connecting": "连接", "connection": "连接",
    "consistency": "一致性", "constant": "常量", "constituent": "组成部分",
    "constrained": "受约束", "constraint": "约束", "construction": "构造",
    "constructive": "构造", "contact": "接触", "contacting": "接触", "context": "上下文",
    "continuous": "连续", "contouring": "轮廓加工", "contract": "合同", "control": "控制",
    "conversion": "转换", "convex": "凸", "coordinates": "坐标", "corner": "角",
    "cos": "余弦", "counterbore": "沉孔", "counterdrill": "沉钻", "countersink": "锥形沉孔",
    "coupling": "耦合", "csg": "构造实体几何", "cubic": "三次", "current": "电流",
    "curve": "曲线", "curves": "曲线", "cutting": "切削", "cyclide": "圆环曲面",
    "cylinder": "圆柱", "cylindrical": "圆柱", "cylindricity": "圆柱度", "d3": "D3",
    "data": "数据", "dataset": "数据集", "date": "日期", "dated": "注明日期",
    "datum": "基准", "decomposition": "分解", "default": "默认", "defined": "定义",
    "defining": "定义", "definite": "确定", "definition": "定义", "definitional": "定义性",
    "degenerate": "退化", "delineation": "轮廓线", "denoted": "被表示", "density": "密度",
    "dependent": "相关", "derivative": "导数", "derived": "派生", "deriving": "派生",
    "description": "描述", "descriptive": "描述", "design": "设计", "designation": "标识",
    "designator": "代号", "diameter": "直径", "dielectric": "介电", "diffuse": "漫反射",
    "dimension": "尺寸", "dimensional": "尺寸", "directed": "有向", "direction": "方向",
    "directional": "方向", "directive": "指令", "disk": "圆盘", "disposed": "布置",
    "div": "整除", "document": "文档", "documents": "文档", "domain": "域",
    "dose": "剂量", "draughting": "制图", "drilling": "钻孔", "dupin": "Dupin",
    "dwell": "停顿", "eccentric": "偏心", "edge": "边", "effectivity": "有效性",
    "electric": "电", "element": "元素", "elementary": "基本", "elements": "元素",
    "ellipse": "椭圆", "ellipsoid": "椭球", "end": "端", "energy": "能量",
    "enum": "枚举", "environment": "环境", "equal": "相等", "equals": "等于",
    "equivalence": "等价", "equivalent": "等效", "evaluated": "求值", "event": "事件",
    "exclusive": "排他", "executable": "可执行", "executed": "已执行", "execution": "执行",
    "exp": "指数函数", "expanded": "展开", "explicit": "显式", "exponents": "指数",
    "expression": "表达式", "extended": "扩展", "extension": "扩展", "extent": "范围",
    "external": "外部", "externally": "外部", "face": "面", "faces": "面",
    "faceted": "分面", "facing": "端面加工", "factor": "因子", "feature": "特征",
    "feed": "进给", "file": "文件", "fill": "填充", "fillet": "圆角", "filter": "过滤",
    "filtration": "过滤", "final": "最终", "finite": "有限", "fits": "配合",
    "fixed": "固定", "fixture": "夹具", "flat": "平面", "flatness": "平面度",
    "flexible": "柔性", "floor": "底", "flux": "通量", "font": "字体", "for": "用于",
    "force": "力", "form": "形状", "format": "格式", "formation": "形成",
    "founded": "基于", "free": "自由", "freeform": "自由曲面", "frequency": "频率",
    "from": "来自", "fully": "完全", "function": "函数", "functional": "功能",
    "functionally": "功能", "functions": "函数", "gear": "齿轮", "general": "通用",
    "generic": "通用", "geometric": "几何", "geometrical": "几何", "geometrically": "几何",
    "geometry": "几何", "global": "全局", "glyph": "字形", "gps": "GPS",
    "greater": "大于", "grid": "网格", "grooving": "切槽", "group": "组", "half": "半",
    "hardness": "硬度", "hatch": "剖面线", "hatching": "剖面线", "header": "头",
    "helix": "螺旋", "hexahedron": "六面体", "hidden": "隐藏", "hierarchical": "层次",
    "high": "高", "higher": "更高", "hlhsr": "消隐", "hole": "孔", "homogeneous": "齐次",
    "homokinetic": "等速", "hyperbola": "双曲线", "id": "标识", "identification": "标识",
    "identified": "被标识", "identifier": "标识符", "idrm": "IDRM", "illuminance": "照度",
    "image": "图像", "imported": "导入", "in": "在", "included": "包含",
    "inclusion": "包含", "index": "索引", "individual": "单个", "inductance": "电感",
    "ineffectivity": "无效性", "information": "信息", "instance": "实例",
    "instanced": "实例化", "instruction": "指令", "int": "整数", "integer": "整数",
    "integral": "积分", "intension": "内涵", "intensities": "强度", "intensity": "强度",
    "interface": "接口", "interpolated": "插值", "intersection": "相交", "interval": "区间",
    "invisibility": "不可见", "involute": "渐开线", "is": "是", "item": "项",
    "joint": "关节", "kinematic": "运动学", "kinematics": "运动学", "knots": "节点",
    "known": "已知", "knurl": "滚花", "knurling": "滚花", "language": "语言",
    "layer": "层", "leader": "指引线", "length": "长度", "less": "小于", "level": "层级",
    "library": "库", "light": "光源", "like": "类似", "limits": "极限", "line": "线",
    "linear": "线性", "linearized": "线性化", "link": "链接", "list": "列表",
    "listed": "列出", "literal": "字面量", "local": "局部", "locally": "局部",
    "location": "位置", "log": "对数", "log10": "常用对数", "log2": "底2对数",
    "logical": "逻辑", "loop": "环", "loss": "损耗", "lot": "批次", "low": "低",
    "luminous": "光", "machine": "机床", "machining": "加工", "magnetic": "磁",
    "make": "制作", "manifold": "流形", "manufacturing": "制造", "map": "映射",
    "mappable": "可映射", "mapped": "已映射", "marker": "标记", "marking": "标记",
    "mass": "质量", "material": "材料", "mathematical": "数学", "maths": "数学",
    "matrix": "矩阵", "max": "最大", "maximum": "最大", "measure": "量",
    "mechanical": "机械", "mechanism": "机构", "membership": "隶属", "method": "方法",
    "milling": "铣削", "min": "最小", "minimum": "最小", "minus": "减", "mirror": "镜像",
    "mod": "取模", "model": "模型", "modified": "修改", "modifier": "修饰符",
    "modifiers": "修饰符", "month": "月", "motion": "运动", "movement": "移动",
    "mult": "乘", "multi": "多", "multiple": "多个", "name": "名称", "named": "命名",
    "nc": "数控", "network": "网络", "next": "下一个", "ngon": "多边形", "node": "节点",
    "nodes": "节点", "non": "非", "normals": "法向量", "not": "非", "null": "空",
    "number": "编号", "numbered": "编号", "numeric": "数值", "object": "对象",
    "occurrence": "实例", "odd": "奇数", "of": "的", "offset": "偏置", "omit": "省略",
    "on": "在", "one": "一", "open": "开放", "operation": "操作", "operator": "运算符",
    "option": "选项", "or": "或", "order": "次序", "ordinal": "序数", "ordinate": "坐标",
    "organization": "组织", "organizational": "组织", "orientation": "定向",
    "oriented": "有向", "outer": "外", "outline": "轮廓", "outside": "外部",
    "over": "覆盖", "package": "包", "pair": "副", "parabola": "抛物线",
    "parallel": "平行", "parallelism": "平行度", "parameter": "参数",
    "parameters": "参数", "parametric": "参数化", "partial": "部分", "patch": "面片",
    "path": "路径", "pattern": "阵列", "pcurve": "参数曲线", "perpendicular": "垂直",
    "perpendicularity": "垂直度", "person": "人员", "personal": "个人", "physical": "物理",
    "pin": "销", "pinion": "小齿轮", "placed": "放置", "placeholder": "占位符",
    "placement": "放置", "plan": "计划", "planar": "平面", "plane": "平面",
    "planned": "计划", "plate": "板", "plus": "加", "pmi": "产品制造信息",
    "pocket": "凹槽", "point": "点", "polar": "极坐标", "poly": "多", "polyline": "折线",
    "position": "位置", "positional": "位置", "positive": "正", "potential": "电位",
    "power": "功率", "pre": "预", "precision": "精度", "prescribed": "规定",
    "presentation": "表示", "presented": "被表示", "pressure": "压力",
    "primitive": "基本体", "prismatic": "棱柱", "probing": "探测", "process": "过程",
    "product": "产品", "profile": "轮廓", "project": "项目", "projected": "投影",
    "projection": "投影", "promissory": "承诺性", "properties": "属性", "property": "属性",
    "protocol": "协议", "protrusion": "凸起", "pyramid": "棱锥", "qualification": "资格",
    "qualified": "限定", "qualifier": "限定符", "qualitative": "定性",
    "quantified": "量化", "quantifier": "量词", "quasi": "拟", "rack": "齿条",
    "radioactivity": "放射性", "radius": "半径", "range": "范围", "rapid": "快速",
    "ratio": "比", "rational": "有理", "rationalize": "有理化", "real": "实数",
    "realization": "实现", "realized": "已实现", "rectangular": "矩形",
    "reference": "引用", "referenced": "被引用", "references": "引用", "refined": "细化",
    "reflectance": "反射率", "region": "区域", "regular": "规则", "reindexed": "重索引",
    "related": "相关", "relationship": "关系", "relative": "相对", "removal": "移除",
    "rendering": "渲染", "rep": "表示", "repackaging": "重新包装",
    "reparametrised": "重参数化", "repeat": "重复", "replica": "复制",
    "replicate": "复制", "repositioned": "重新定位", "representation": "表示",
    "request": "请求", "requirement": "要求", "resistance": "电阻", "resource": "资源",
    "restriction": "限制", "result": "结果", "resulting": "结果", "retention": "保持",
    "retract": "退回", "revision": "修订", "revolute": "旋转", "revolution": "回转",
    "revolved": "回转", "rgb": "RGB", "rib": "加强筋", "riding": "啮合", "right": "右",
    "rigid": "刚性", "role": "角色", "rolling": "滚动", "root": "根",
    "rotation": "旋转", "round": "圆", "rounded": "圆角", "roundness": "圆度",
    "row": "行", "ruled": "直纹", "runout": "跳动", "same": "相同",
    "satisfied": "被满足", "satisfies": "满足", "satisfying": "满足", "scale": "比例",
    "scaling": "缩放", "scan": "扫描", "scanned": "扫描", "scanner": "扫描仪",
    "screw": "螺旋", "seam": "接缝", "security": "安全", "segment": "段",
    "segmentation": "分段", "selector": "选择器", "semantics": "语义",
    "sequence": "序列", "sequential": "顺序", "serial": "串行", "series": "系列",
    "set": "集合", "setup": "设置", "shaded": "着色", "shape": "形状", "shell": "壳",
    "si": "SI", "side": "侧", "silhouette": "轮廓", "simple": "简单",
    "simplified": "简化", "sin": "正弦", "single": "单个", "size": "尺寸",
    "slash": "斜线", "sliding": "滑动", "slot": "槽", "solid": "实体",
    "solution": "解", "source": "源", "sourced": "有来源", "sources": "源",
    "space": "空间", "spacing": "间距", "sparse": "稀疏", "specific": "特定",
    "specification": "规范", "specified": "指定", "specular": "镜面", "speed": "速度",
    "sphere": "球", "spherical": "球形", "spindle": "主轴", "spline": "样条",
    "spot": "点", "spotface": "锪平面", "sql": "SQL", "square": "方形",
    "standard": "标准", "state": "状态", "status": "状态", "step": "步",
    "straightness": "直线度", "strategy": "策略", "strict": "严格", "string": "字符串",
    "stroke": "笔画", "structure": "结构", "structured": "结构化", "style": "样式",
    "styled": "带样式", "su": "SU", "sub": "子", "subedge": "子边", "subface": "子面",
    "subfigure": "子图", "subpath": "子路径", "substance": "物质",
    "substitute": "替代", "substring": "子串", "substructure": "子结构",
    "subsurface": "子曲面", "superdataset": "超数据集", "support": "支持",
    "surface": "曲面", "swept": "扫掠", "symbol": "符号", "symmetric": "对称",
    "symmetry": "对称度", "system": "系统", "table": "表", "tactile": "触觉",
    "tagged": "带标记", "tan": "正切", "tangent": "相切", "taper": "锥度",
    "tapping": "攻丝", "target": "目标", "technology": "技术", "tee": "T形",
    "temperature": "温度", "terminator": "终止符", "tessellated": "镶嵌",
    "tetrahedron": "四面体", "text": "文本", "texture": "纹理", "thermal": "热",
    "thermodynamic": "热力学", "thread": "螺纹", "threading": "车螺纹", "tile": "瓦片",
    "tiles": "瓦片", "time": "时间", "to": "到", "tolerance": "公差", "tool": "刀具",
    "toolpath": "刀路", "top": "顶部", "topological": "拓扑", "topology": "拓扑",
    "toroidal": "环面", "torus": "圆环面", "total": "总", "touch": "接触",
    "transformation": "变换", "transition": "过渡", "transparent": "透明",
    "tree": "树", "triangular": "三角", "triangulated": "三角剖分", "trimmed": "裁剪",
    "tuple": "元组", "turned": "车削", "turning": "车削", "twin": "双", "two": "二",
    "type": "类型", "u": "U", "unary": "一元", "uncertainty": "不确定度",
    "unconstrained": "无约束", "unequally": "不等", "uniform": "均匀", "union": "并集",
    "unit": "单位", "universal": "通用", "usage": "用法", "user": "用户",
    "value": "值", "variable": "变量", "vector": "向量", "vee": "V形",
    "velocity": "速度", "version": "版本", "versioned": "多版本", "vertex": "顶点",
    "via": "经由", "view": "视图", "visual": "视觉", "voids": "空腔",
    "volume": "体积", "wedge": "楔", "wire": "线", "wireframe": "线框", "with": "带",
    "within": "之内", "workingstep": "工步", "workpiece": "工件", "workplan": "工作计划",
    "xor": "异或", "year": "年", "zone": "区域",
}

# 重点概念的人工译名（覆盖自动组合结果）
OVERRIDES = {
    # —— 表示 / 框架 ——
    "representation": "表示", "representation_item": "表示项",
    "representation_context": "表示上下文", "representation_relationship": "表示关系",
    "representation_map": "表示映射", "shape_representation": "形状表示",
    "product_definition_shape": "产品定义形状", "property_definition": "属性定义",
    "property_definition_representation": "属性定义表示", "context_dependent_shape_representation": "上下文相关的形状表示",
    "product_definition": "产品定义", "product_definition_formation": "产品定义版本",
    "product_definition_relationship": "产品定义关系", "product_definition_usage": "产品定义用法",
    "product_definition_occurrence": "产品定义实例", "product_definition_context": "产品定义上下文",
    "geometric_representation_context": "几何表示上下文", "geometric_representation_item": "几何表示项",
    "shape_definition_representation": "形状定义表示", "manifold_solid_brep": "流形实体边界表示",
    "advanced_brep_shape_representation": "高级边界表示形状表示",
    "shape_aspect": "形状要素", "shape_aspect_relationship": "形状要素关系",
    "product_definition_element_relationship": "产品定义元素关系",
    # —— 尺寸（3D 空间尺寸 / PMI）——
    "dimensional_size": "尺寸（dimensional size）",
    "dimensional_size_with_path": "带路径的尺寸",
    "dimensional_size_with_datum_feature": "以基准要素定义的尺寸",
    "dimensional_location": "位置尺寸（dimensional location）",
    "dimensional_location_with_path": "带路径的位置尺寸",
    "dimensional_location_with_datum_feature": "以基准要素定义的位置尺寸",
    "directed_dimensional_location": "有向位置尺寸",
    "dimensional_characteristic_representation": "尺寸特征表示",
    "shape_dimension_representation": "尺寸几何表示",
    "shape_dimension_representation_item": "尺寸几何表示项",
    "dimensional_characteristic": "尺寸特征",
    # —— 尺寸标注（2D 图纸）——
    "dimension_callout": "尺寸标注注记",
    "dimension_callout_relationship": "尺寸标注注记关系",
    "dimension_callout_component_relationship": "尺寸标注注记组成关系",
    "structured_dimension_callout": "结构化尺寸注记",
    "angular_dimension": "角度尺寸",
    "linear_dimension": "线性尺寸",
    "ordinate_dimension": "坐标尺寸",
    "radius_dimension": "半径尺寸",
    "diameter_dimension": "直径尺寸",
    "curve_dimension": "曲线尺寸",
    "leader_directed_dimension": "指引线尺寸",
    "dimension_curve": "尺寸线",
    "dimension_curve_directed_callout": "尺寸线有向注记",
    "dimension_curve_terminator": "尺寸线终止符",
    "dimension_curve_terminator_to_projection_curve_associativity": "尺寸线终止符到投影曲线的关联",
    "dimension_text_associativity": "尺寸文本关联",
    "dimension_pair": "尺寸对",
    "dimension_count": "尺寸个数",
    "dimension_extent_usage": "尺寸范围用法",
    "dimension_related_tolerance_zone_element": "与尺寸相关的公差带元素",
    "pre_defined_dimension_symbol": "预定义尺寸符号",
    "externally_defined_dimension_definition": "外部定义的尺寸定义",
    "dimension_tolerance": "尺寸公差",
    # —— 公差 ——
    "geometric_tolerance": "几何公差",
    "geometric_tolerance_relationship": "几何公差关系",
    "geometric_tolerance_with_datum_reference": "带基准的几何公差",
    "geometric_tolerance_with_modifiers": "带修饰符的几何公差",
    "geometric_tolerance_with_defined_unit": "带定义单位的几何公差",
    "geometric_tolerance_with_defined_area_unit": "带定义面积单位的几何公差",
    "geometric_tolerance_with_maximum_tolerance": "带最大公差的几何公差",
    "geometric_tolerance_auxiliary_classification": "几何公差辅助分类",
    "modified_geometric_tolerance": "修改的几何公差",
    "unequally_disposed_geometric_tolerance": "不等布置的几何公差",
    "flatness_tolerance": "平面度公差", "straightness_tolerance": "直线度公差",
    "roundness_tolerance": "圆度公差", "cylindricity_tolerance": "圆柱度公差",
    "line_profile_tolerance": "线轮廓度公差", "surface_profile_tolerance": "面轮廓度公差",
    "angularity_tolerance": "倾斜度公差", "parallelism_tolerance": "平行度公差",
    "perpendicularity_tolerance": "垂直度公差", "position_tolerance": "位置度公差",
    "concentricity_tolerance": "同轴度公差", "symmetry_tolerance": "对称度公差",
    "circular_runout_tolerance": "圆跳动公差", "total_runout_tolerance": "全跳动公差",
    "plus_minus_tolerance": "正负公差", "tolerance_value": "公差值",
    "tolerance_value_or_limits_and_fits": "公差值或极限与配合",
    "tolerance_zone": "公差带", "tolerance_zone_form": "公差带形状",
    "tolerance_zone_definition": "公差带定义", "tolerance_zone_with_datum": "带基准的公差带",
    "directed_tolerance_zone": "有向公差带", "oriented_tolerance_zone": "定向公差带",
    "geometrical_tolerance_callout": "几何公差注记",
    "pre_defined_geometrical_tolerance_symbol": "预定义几何公差符号",
    # —— 基准 ——
    "datum": "基准", "datum_feature": "基准要素", "datum_system": "基准体系",
    "datum_target": "基准目标", "datum_reference": "基准引用",
    "datum_reference_compartment": "基准引用格",
    "datum_reference_element": "基准引用元素",
    "datum_reference_modifier_with_value": "带值的基准引用修饰符",
    "general_datum_reference": "公共基准引用",
    "referenced_modified_datum": "被引用的修改基准",
    "datum_feature_callout": "基准要素注记", "datum_target_callout": "基准目标注记",
    "common_datum": "公共基准", "placed_datum_target_feature": "放置的基准目标要素",
    "feature_for_datum_target_relationship": "基准目标要素关系",
    # —— 标注 / 制图 ——
    "annotation_occurrence": "标注实例", "annotation_occurrence_associativity": "标注实例关联",
    "annotation_occurrence_relationship": "标注实例关系",
    "draughting_callout": "制图注记", "draughting_callout_relationship": "制图注记关系",
    "leader_directed_callout": "指引线注记", "projection_directed_callout": "投影有向注记",
    "draughting_model": "制图模型", "draughting_element": "制图元素",
    "draughting_annotation_occurrence": "制图标注实例",
    "draughting_model_item_association": "制图模型项关联",
    "annotation_text": "标注文本", "annotation_text_occurrence": "标注文本实例",
    "annotation_symbol": "标注符号", "annotation_symbol_occurrence": "标注符号实例",
    "annotation_plane": "标注平面", "annotation_fill_area": "标注填充区域",
    "annotation_curve_occurrence": "标注曲线实例",
    "annotation_to_model_leader_line": "标注到模型的指引线",
    "annotation_to_annotation_leader_line": "标注到标注的指引线",
    "presentation_area": "表示区域", "presentation_view": "表示视图",
    "presentation_layer_assignment": "表示图层赋值",
    "tessellated_annotation_occurrence": "镶嵌标注实例",
    "structured_text_composition": "结构化文本组成", "composite_text": "复合文本",
    "text_literal": "文本字面量", "text_style": "文本样式",
    "draughting_text_literal_with_delineation": "带轮廓线的制图文本字面量",
    # —— 几何 / 拓扑 ——
    "cartesian_point": "笛卡儿点", "point": "点", "direction": "方向",
    "vector": "向量", "axis1_placement": "轴1放置", "axis2_placement_3d": "三维轴2放置",
    "b_spline_curve": "B 样条曲线", "b_spline_surface": "B 样条曲面",
    "rational_b_spline_curve": "有理 B 样条曲线", "rational_b_spline_surface": "有理 B 样条曲面",
    "curve": "曲线", "surface": "曲面", "solid_model": "实体模型",
    "advanced_face": "高级面", "face_surface": "面曲面", "edge_curve": "边曲线",
    "vertex_point": "顶点(点)", "closed_shell": "闭合壳", "open_shell": "开放壳",
    "connected_face_set": "连接面集合", "shell_based_surface_model": "基于壳的曲面模型",
    "geometric_set": "几何集合", "geometric_curve_set": "几何曲线集合",
    "geometric_model": "几何模型", "geometric_model_schema": "几何模型模式",
    "tessellated_item": "镶嵌项", "tessellated_shape_representation": "镶嵌形状表示",
    "trimmed_curve": "裁剪曲线", "offset_curve_2d": "二维偏置曲线",
    "composite_curve": "组合曲线", "composite_curve_segment": "组合曲线段",
    "pcurve": "参数曲线", "surfaced_shape_model": "带曲面形状模型",
    # —— 度量 / 单位 ——
    "measure_with_unit": "带单位的量", "measure_value": "量值",
    "length_measure": "长度量", "plane_angle_measure": "平面角度量",
    "positive_length_measure": "正长度量", "positive_plane_angle_measure": "正平面角度量",
    "ratio_measure": "比量", "count_measure": "计数测量", "descriptive_measure": "描述性度量",
    "si_unit": "SI 单位", "derived_unit": "导出单位", "named_unit": "具名单位",
    "uncertainty_measure_with_unit": "不确定度量（带单位）",
    # —— 产品 / 管理 ——
    "product": "产品", "product_definition_formation_with_specified_source": "带指定来源的产品定义版本",
    "configuration_item": "配置项", "product_concept": "产品概念",
    "product_concept_feature": "产品概念特征", "product_category": "产品类别",
    "approval": "批准", "certification": "认证", "contract": "合同",
    "document": "文档", "effectivity": "有效性", "organization": "组织",
    "person": "人员", "security_classification": "安全密级",
    "action": "动作", "action_method": "动作方法", "action_property": "动作属性",
    "applied_action_assignment": "应用动作赋值",
    "date": "日期", "calendar_date": "日历日期",
    # —— 运动学 / 加工 ——
    "kinematic_pair": "运动副", "kinematic_link": "运动连杆",
    "kinematic_structure": "运动学结构", "kinematic_path": "运动学路径",
    "machining_feature": "加工特征", "machining_operation": "加工操作",
    "machining_workingstep": "加工工步", "machining_process_plan": "加工工艺计划",
    "machining_tool": "加工刀具", "machining_feature_relationship": "加工特征关系",
    "round_hole": "圆通孔", "counterbore_hole": "沉孔", "countersink_hole": "锥形沉孔",
    "spotface_hole": "锪平孔", "threaded_hole": "螺纹孔",
    "workpiece": "工件", "nc_function": "数控功能", "toolpath": "刀路",
    # —— 表达式函数 ——
    "expression": "表达式", "abs_function": "绝对值函数", "acos_function": "反余弦函数",
    "asin_function": "反正弦函数", "atan_function": "反正切函数", "cos_function": "余弦函数",
    "sin_function": "正弦函数", "tan_function": "正切函数", "exp_function": "指数函数",
    "log_function": "对数函数", "log2_function": "底2对数函数", "log10_function": "常用对数函数",
    "sqrt_function": "平方根函数", "plus_expression": "加法表达式",
    "minus_expression": "减法表达式", "mult_expression": "乘法表达式",
    "div_expression": "除法表达式", "mod_expression": "取模表达式",
    "concat_expression": "连接表达式", "substring_expression": "子串表达式",
    "length_function": "长度函数", "value_function": "取值函数",
    "variable": "变量", "numeric_variable": "数值变量", "literal": "字面量",
    "real_literal": "实数字面量", "integer_literal": "整数字面量",
    "boolean_literal": "布尔字面量", "string_literal": "字符串字面量",
    "simple_generic_expression": "简单通用表达式", "enumeration_reference": "枚举引用",
    "unary_numeric_expression": "一元数值表达式", "binary_numeric_expression": "二元数值表达式",
}

# 仅出现在虚线框（DEFINED TYPE / SELECT 类型）等其他名称中的词条
TOKENS.update({
    "8": "8", "ahead": "前", "behind": "后", "bit": "位", "central": "中心",
    "chained": "链式", "chordal": "弦", "classified": "已分类", "code": "代码",
    "count": "个数", "day": "日", "des": "DES", "deviation": "偏差", "dotted": "带点",
    "enumeration": "枚举", "enumerators": "枚举项", "express": "EXPRESS", "facet": "面片",
    "groupable": "可分组", "height": "高", "hour": "小时", "independent": "独立",
    "input": "输入", "interpolation": "插值", "invisible": "不可见", "items": "项",
    "knot": "节点", "label": "标签", "layered": "分层", "limit": "极限",
    "linearly": "线性", "long": "长", "lower": "下", "marked": "带标记",
    "message": "消息", "minute": "分钟", "negative": "负", "nonnegative": "非负",
    "operand": "操作数", "options": "选项", "ordering": "排序", "preference": "优先",
    "preferred": "首选", "prefix": "前缀", "presentable": "可呈现", "proxy": "代理",
    "relator": "关系词", "render": "渲染", "repackage": "重新包装",
    "represented": "被表示", "reversible": "可逆", "rotate": "旋转",
    "satisfaction": "满足", "scaled": "缩放", "second": "秒", "select": "选择类型",
    "shading": "着色", "short": "短", "slant": "斜", "spatial": "空间",
    "superset": "超集", "supported": "受支持", "tessellation": "镶嵌",
    "trimming": "裁剪", "unsigned": "无符号", "upper": "上", "v": "V",
    "values": "值", "week": "周", "width": "宽", "ypr": "YPR", "zero": "零",
})

OVERRIDES.update({
    "point_cloud_dataset": "点云数据集", "point_cloud_set_or_superset": "点云集合或超集",
    "point_cloud_superdataset": "点云超数据集",
    "cartesian_complex_number_region": "笛卡儿复数区域",
    "edge_round": "边圆角", "revolved_area_solid": "回转面实体",
    "wire_shell": "线框壳（wire shell）", "axis2_placement_2d": "二维轴2放置",
    "between_shape_aspect": "形状要素之间", "odd_function": "奇函数",
    "binary_function_call": "二元函数调用", "runout_zone_definition": "跳动公差带定义",
    "surface_style_fill_area": "曲面样式填充区域",
    "next_assembly_usage_occurrence": "下级装配用法实例",
    "low_order_kinematic_pair": "低阶运动副",
    "inclusion_product_concept_feature": "内含产品概念特征",
    "serial_numbered_effectivity": "序号有效性",
    "hour_in_day": "一天中的小时", "minute_in_hour": "一小时中的分钟",
    "second_in_minute": "一分钟中的秒", "day_in_month_number": "月中的日",
    "month_in_year_number": "年中的月", "week_in_year_number": "年中的周",
    "day_in_week_number": "周中的日", "day_in_year_number": "年中的日",
    "year_number": "年份", "zero_or_one": "零或一", "one_or_two": "一或二",
    "u_direction_count": "U 方向个数", "v_direction_count": "V 方向个数",
    "positive_integer": "正整数", "nonnegative_integer": "非负整数",
    "atom_based_tuple": "基于原子的元组",
    "dotted_express_identifier": "带点的 EXPRESS 标识符",
    "presentable_text": "可呈现文本", "text_alignment": "文本对齐",
    "text_delineation": "文本轮廓线", "input_selector": "输入选择器",
    "spline_knot_values": "样条节点值", "value_format_type": "值格式类型",
    "ypr_rotation": "YPR 旋转", "unsigned_8_bit_integer": "无符号 8 位整数",
    "angular_deviation": "角度偏差", "chordal_deviation": "弦偏差",
    "length_to_height_ratio": "长高比", "maximum_edge_length": "最大边长",
    "tessellated_facet_long_short_edge_ratio": "镶嵌面片长短边比",
    "box_height": "盒高", "box_width": "盒宽", "box_rotate_angle": "盒旋转角",
    "box_slant_angle": "盒斜角",
    "list_of_reversible_topology_item": "可逆拓扑项列表",
    "set_of_reversible_topology_item": "可逆拓扑项集合",
    "list_representation_item": "列表表示项", "set_representation_item": "集合表示项",
    "product_definition_or_reference_or_occurrence": "产品定义或引用或实例",
    "message": "消息", "label": "标签", "text": "文本", "identifier": "标识符",
    "common_datum_list": "公共基准列表",
    "context_dependent_measure": "上下文相关的量", "parameter_value": "参数值",
    "numeric_measure": "数值量", "non_negative_length_measure": "非负长度量",
    "celsius_temperature_measure": "摄氏温度量", "dose_equivalent_measure": "剂量当量",
    "solid_angle_measure": "立体角量",
})

# DEFINED TYPE（度量类型 / 基础类型）人工译名，避免出现「电容量」这类冗余
OVERRIDES.update({
    "absorbed_dose_measure": "吸收剂量", "acceleration_measure": "加速度",
    "amount_of_substance_measure": "物质的量", "area_measure": "面积量",
    "capacitance_measure": "电容值", "celsius_temperature_measure": "摄氏温度",
    "conductance_measure": "电导值", "count_measure": "计数量",
    "descriptive_measure": "描述性度量", "dose_equivalent_measure": "剂量当量",
    "electric_charge_measure": "电荷量", "electric_current_measure": "电流值",
    "electric_potential_measure": "电位值", "energy_measure": "能量值",
    "force_measure": "力值", "frequency_measure": "频率值", "illuminance_measure": "照度值",
    "inductance_measure": "电感值", "length_measure": "长度量",
    "luminous_flux_measure": "光通量值", "luminous_intensity_measure": "发光强度值",
    "magnetic_flux_density_measure": "磁通密度值", "magnetic_flux_measure": "磁通量值",
    "mass_measure": "质量值", "non_negative_length_measure": "非负长度量",
    "numeric_measure": "数值量", "plane_angle_measure": "平面角度量",
    "positive_length_measure": "正长度量", "positive_plane_angle_measure": "正平面角度量",
    "positive_ratio_measure": "正比值", "power_measure": "功率值",
    "pressure_measure": "压力值", "radioactivity_measure": "放射性活度",
    "ratio_measure": "比值", "resistance_measure": "电阻值",
    "thermodynamic_temperature_measure": "热力学温度", "time_measure": "时间值",
    "velocity_measure": "速度值", "volume_measure": "体积量",
    "dimension_count": "尺寸个数", "si_prefix": "SI 前缀",
    "maths_binary": "数学二进制", "maths_boolean": "数学布尔", "maths_integer": "数学整数",
    "maths_logical": "数学逻辑", "maths_number": "数学数", "maths_real": "数学实数",
    "maths_string": "数学字符串", "maths_tuple": "数学元组",
    "presentation_representation_select": "presentation 表示选择类型",
})